/// Global textile fibre production and world population by year, 1970-2018. One row per fibre series per year. Backs the fibre-production line/area chart.
table 'Fibre Production 1970-2018'
	lineageTag: 6918a349-0e4d-55ee-af0e-897483b1b7bf

	/// Fibre production series. One of: Cotton, Polyester, Total Fibres, Population (Population is the world-population overlay, in billions).
	column Fibre
		dataType: string
		lineageTag: e18a6259-8184-514d-b1f4-3ca669719e85
		summarizeBy: none
		sourceColumn: Fibre

		annotation SummarizationSetBy = Automatic

	/// Calendar year of the observation, 1970-2018 (annual).
	column Year
		dataType: int64
		lineageTag: 81938c4b-af61-5028-af83-9e312a6c42e9
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	/// Annual fibre production volume, in millions of tonnes per year.
	column 'Production (m tons per year)'
		dataType: double
		lineageTag: 1060df48-98d0-54e4-93de-86709e07771b
		summarizeBy: sum
		sourceColumn: Production (m tons per year)

		annotation SummarizationSetBy = Automatic

	/// World population for the year, in billions (overlay series plotted against fibre production).
	column 'Population (billions)'
		dataType: double
		lineageTag: e41a2344-f8b3-5723-9e29-91e690e0c60f
		summarizeBy: sum
		sourceColumn: Population (billions)

		annotation SummarizationSetBy = Automatic

	partition 'Fibre Production 1970-2018' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "ds.fibre_production_1970_2018_fast_fashion_data_final.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Fibre", type text}, {"Year", Int64.Type}, {"Production (m tons per year)", type number}, {"Population (billions)", type number}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

