/// Water-use value table: share of total water use (%) at each of the 4 water-use stages, keyed by ID 0-3. Drives the water-droplet silhouette; joined from Polygon water on Category.
table 'JEANS water'
	lineageTag: f047bf0c-705f-5ef5-a42a-ba3c93edd883

	/// Water-use stage key, 0-3.
	column ID
		dataType: int64
		lineageTag: 8311f775-dec9-525e-8f0b-7194da660ed8
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	/// Water-use stage. One of: Raw Materials, Fabric Mill, Industrial Laundry, Consumer wash. Join key from Polygon water[Category].
	column Category
		dataType: string
		lineageTag: c6110742-eaff-5623-a6b5-15dbf49693c6
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	/// Share of total water use for this stage, in percent.
	column 'Value (%)'
		dataType: double
		lineageTag: 0b2e4f6c-9424-553a-adb1-44966255c937
		summarizeBy: sum
		sourceColumn: Value (%)

		annotation SummarizationSetBy = Automatic

	partition 'JEANS water' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "ds.jeans_water_fast_fashion_data_final.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"ID", Int64.Type}, {"Category", type text}, {"Value (%)", type number}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

