/// Polygon (x/y point-path) geometry for the jeans/CO2 silhouette, one shape per lifecycle stage. 223 vertices across 8 shapes; joins to JEANS on Shape Id.
table 'Jeans Polygon'
	lineageTag: 50065752-8b03-533f-9a0c-7ccd601390c2

	/// Shape identifier 0-7; one shape per jeans lifecycle stage. Foreign key to JEANS[ID].
	column 'Shape Id'
		dataType: int64
		lineageTag: 8b55953b-b305-5b49-bf4b-9365e83cf755
		summarizeBy: none
		sourceColumn: shapeId

		annotation SummarizationSetBy = Automatic

	/// Geometry primitive type. Always 'polygon'.
	column 'Shape Type'
		dataType: string
		lineageTag: 079794b5-9246-50db-8f9e-e560da701e4c
		summarizeBy: none
		sourceColumn: shapeType

		annotation SummarizationSetBy = Automatic

	/// Optional per-shape text label (unused / empty in this extract).
	column 'Shape Label'
		dataType: string
		lineageTag: 54f6315f-4378-5832-aa98-10b3290ee957
		summarizeBy: none
		sourceColumn: shapeLabel

		annotation SummarizationSetBy = Automatic

	/// Sequential vertex index (0-99) tracing the polygon outline; draw order.
	column 'Point Id'
		dataType: int64
		lineageTag: f01d5087-3ce1-58c3-b311-98bcfb6cd954
		summarizeBy: none
		sourceColumn: pointId

		annotation SummarizationSetBy = Automatic

	/// Vertex X coordinate (screen space) of the jeans silhouette outline.
	column 'Point X'
		dataType: int64
		lineageTag: fc771c7d-dd2f-5ad4-9709-4a031e9c9ad8
		summarizeBy: none
		sourceColumn: pointX

		annotation SummarizationSetBy = Automatic

	/// Vertex Y coordinate (screen space) of the jeans silhouette outline.
	column 'Point Y'
		dataType: int64
		lineageTag: 23a582a4-2642-58e2-b4a0-eb00da00e671
		summarizeBy: none
		sourceColumn: pointY

		annotation SummarizationSetBy = Automatic

	/// Jeans garment-lifecycle stage this shape represents. One of: Cotton Production, Yarn Production, Garment Production, Distribution and retailing, User phase, End of life.
	column Category
		dataType: string
		lineageTag: 4b6c7fc2-7b40-537b-af9b-b2c09b4ce2eb
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	/// Share of total environmental impact for this lifecycle stage, in percent.
	column 'Value (%)'
		dataType: double
		lineageTag: f8c45e69-fa21-5c19-ab19-f855171ae14d
		summarizeBy: sum
		sourceColumn: Value (%)

		annotation SummarizationSetBy = Automatic

	/// Point X mirrored horizontally (Point X x -1) so the silhouette faces the intended direction. Derived.
	column 'Point X Flipped' = 'Jeans Polygon'[Point X] * -1
		dataType: int64
		lineageTag: 8fc62a9f-f616-5287-8f35-bd7aeca3b8ad
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Jeans Polygon' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "ds.jeans_polygon_fast_fashion_data_final.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"shapeId", Int64.Type}, {"shapeType", type text}, {"shapeLabel", type text}, {"pointId", Int64.Type}, {"pointX", Int64.Type}, {"pointY", Int64.Type}, {"Category", type text}, {"Value (%)", type number}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

