/// Jeans garment-lifecycle value table: share of total environmental impact (%) at each lifecycle stage, keyed by ID 0-7. Drives the jeans/CO2 silhouette; joined from Jeans Polygon.
table JEANS
	lineageTag: a29d6c68-3c6e-5bdb-aa5d-be144aafd738

	/// Jeans lifecycle-stage key, 0-7. Join key from Jeans Polygon[Shape Id].
	column ID
		dataType: int64
		lineageTag: de404173-7947-5c49-8fde-dc0f2d651a79
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	/// Jeans garment-lifecycle stage. One of: Cotton Production, Yarn Production, Garment Production, Distribution and retailing, User phase, End of life.
	column Category
		dataType: string
		lineageTag: 028a6c75-7409-576f-b683-27434ca5964c
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	/// Share of total environmental impact for this lifecycle stage, in percent.
	column 'Value (%)'
		dataType: double
		lineageTag: e8e5dc46-72f7-593e-9fd1-5769f23f1c06
		summarizeBy: sum
		sourceColumn: Value (%)

		annotation SummarizationSetBy = Automatic

	partition JEANS = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "ds.jeans_fast_fashion_data_final.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"ID", Int64.Type}, {"Category", type text}, {"Value (%)", type number}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

