/// Polygon geometry for the fibre-materials silhouette, one shape per material category with its share (%). 201 vertices across 5 shapes. Self-contained (Category + Value % baked in).
table 'Polygon Materials'
	lineageTag: 28e225bc-1556-5928-9fb6-fc5736fe6b50

	/// Shape identifier 0-4; one shape per material category.
	column 'Shape Id'
		dataType: int64
		lineageTag: a2fcc0fd-f5d5-575c-b98b-803fa9f9b436
		summarizeBy: none
		sourceColumn: shapeId

		annotation SummarizationSetBy = Automatic

	/// Geometry primitive type. Always 'polygon'.
	column 'Shape Type'
		dataType: string
		lineageTag: 450d4549-64d3-5a83-bd6f-0ba00ff4656a
		summarizeBy: none
		sourceColumn: shapeType

		annotation SummarizationSetBy = Automatic

	/// Sequential vertex index (0-99) tracing the polygon outline; draw order.
	column 'Point Id'
		dataType: int64
		lineageTag: 375e0f82-39e5-5ab0-9a7e-5d9f72049318
		summarizeBy: none
		sourceColumn: pointId

		annotation SummarizationSetBy = Automatic

	/// Vertex X coordinate (screen space) of the materials silhouette outline.
	column 'Point X'
		dataType: int64
		lineageTag: 33e61667-bfd6-5dec-8ccf-f4a9ffc1e857
		summarizeBy: none
		sourceColumn: pointX

		annotation SummarizationSetBy = Automatic

	/// Vertex Y coordinate (screen space) of the materials silhouette outline.
	column 'Point Y'
		dataType: int64
		lineageTag: 1086815c-1f0f-57e6-9660-3313e39eb17b
		summarizeBy: none
		sourceColumn: pointY

		annotation SummarizationSetBy = Automatic

	/// Fibre-material category. One of: Cotton, Polymer synthetics, Wood-based synthetics.
	column Category
		dataType: string
		lineageTag: 83f90849-f114-5738-b88f-d983f55c7705
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	/// Share of total fibre materials for this category, in percent.
	column 'Value (%)'
		dataType: double
		lineageTag: e1f99400-03a9-58bd-a049-b3f36cc03a05
		summarizeBy: sum
		sourceColumn: Value (%)

		annotation SummarizationSetBy = Automatic

	/// Point X mirrored horizontally (Point X x -1). Derived.
	column 'Point X Flipped' = 'Polygon Materials'[Point X] * -1
		dataType: int64
		lineageTag: 2fd16848-d848-5f2b-94ec-d30f2723e411
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Polygon Materials' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "ds.polygon_materials_fast_fashion_data_final.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"shapeId", Int64.Type}, {"shapeType", type text}, {"pointId", Int64.Type}, {"pointX", Int64.Type}, {"pointY", Int64.Type}, {"Category", type text}, {"Value (%)", type number}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

