/// Polygon geometry for the 'consumer importance' ripped-paper silhouette, segmented by importance level. 115 vertices across 5 shapes.
table 'Ripped Polygon'
	lineageTag: f21848ea-8c08-5e48-902c-85c656d454e2

	/// Shape identifier 1-5; one shape per consumer-importance level.
	column 'Shape Id'
		dataType: int64
		lineageTag: c97094af-1301-59d1-a898-d14e3de19e72
		summarizeBy: none
		sourceColumn: shapeId

		annotation SummarizationSetBy = Automatic

	/// Geometry primitive type. Always 'polygon'.
	column 'Shape Type'
		dataType: string
		lineageTag: 18f16a54-4546-557a-bb37-a37dbabf3fde
		summarizeBy: none
		sourceColumn: shapeType

		annotation SummarizationSetBy = Automatic

	/// Sequential vertex index tracing the ripped-paper outline; draw order.
	column 'Point Id'
		dataType: int64
		lineageTag: 1d01e254-870d-5f46-b3d3-adc178694d0f
		summarizeBy: none
		sourceColumn: pointId

		annotation SummarizationSetBy = Automatic

	/// Vertex X coordinate (screen space) of the ripped-paper silhouette.
	column 'Point X'
		dataType: int64
		lineageTag: 57662865-fe4a-5c6d-80e7-afd9ada8a379
		summarizeBy: none
		sourceColumn: pointX

		annotation SummarizationSetBy = Automatic

	/// Vertex Y coordinate (screen space) of the ripped-paper silhouette.
	column 'Point Y'
		dataType: int64
		lineageTag: b25061f4-de75-5204-be5b-1bc7de21a04d
		summarizeBy: none
		sourceColumn: pointY

		annotation SummarizationSetBy = Automatic

	/// Consumer-importance rating of sustainability. One of: Extremely important, Very important, Somewhat important, Neutral, Not at all important.
	column Importance
		dataType: string
		lineageTag: 3324adbe-2e1b-5838-88ca-b7aa0af1cfc4
		summarizeBy: none
		sourceColumn: Importance

		annotation SummarizationSetBy = Automatic

	/// Percentage of consumers giving this importance rating.
	column Value
		dataType: int64
		lineageTag: fb512b38-b9ab-549f-8d24-702dcd515b51
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Ripped Polygon' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "ds.ripped_polygon_consumer_importance.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"shapeId", Int64.Type}, {"shapeType", type text}, {"pointId", Int64.Type}, {"pointX", Int64.Type}, {"pointY", Int64.Type}, {"Importance", type text}, {"Value", Int64.Type}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

