"""Direct #562 prerequisite controls, not an implementation of the final START_READY consumer.

Hand-built S1/S2 fixtures and literal projection/key oracles separate bytes, binding and applicability.
No audit, credential change, probe, source search, provider permission or final readiness fold here.
"""

from __future__ import annotations

import copy
import hashlib
import inspect
import json
import os
import shutil
import stat
from dataclasses import fields, replace
from pathlib import Path

import pytest

from test_package_filesystem import build_package, classify, link_directory, verify, write_manifest
from test_package_role_identity import (
    DS_LUID,
    PUBLISHED_KEY,
    WB_LUID,
    datasource_package,
    pri,
    seal,
    workbook_package,
)

import credential_gate as gate
import package_filesystem as pfs

# pylint: disable=protected-access,missing-function-docstring

SPEC = "migration-spec.json"
PROJECTION = "data-access.json"
LIVE = {"class": "sqlserver", "server": "source.example", "database": "db", "powerbi_target": "live_source"}
OTHER = {**LIVE, "server": "other.example"}
FLAT = {"class": "excel-direct", "powerbi_target": "flat_file"}
REVIEW = {"class": "unknown", "server": "review.example", "powerbi_target": "unknown"}
# Independent SHA-256 of the canonical endpoint JSON, not generated by package_spec_facts().
LIVE_KEY = "source-key:ab1baa4b3f77bb70"
OTHER_KEY = "source-key:e625ce798a6d19bb"
LOCAL_PROJECTION = {
    "schema": "phase1-data-access/v1",
    "state": "local_import_ready",
    "source_keys": [],
    "provider_unit": None,
    "provider_state": None,
    "validation": "validated",
    "effective_scope": "model_only",
    "max_phase2_claim": "data_validated",
    "codes": ["all-flat-file", "package-self-contained"],
}
LIVE_PROJECTION = {
    **LOCAL_PROJECTION,
    "state": "live_data_ok",
    "source_keys": [LIVE_KEY],
    "codes": ["probe-cleared", "probe-data-ok"],
}
PUBLISHED = {
    "id": "ds",
    "connection": {"class": "sqlproxy", "mode": "live", "powerbi_target": "flat_file"},
    "published_datasource": {"luid": DS_LUID, "key": PUBLISHED_KEY},
}


def source_rows(*connections: dict) -> list[dict]:
    """A minimal spec row, retaining real canonical connection classification."""
    return [{"connection": dict(connection), "tables": [], "fields": []} for connection in connections]


def with_data_access(package: Path, rows: list | None = None, projection: dict | bytes | None = None) -> Path:
    """Declare exact role bytes without invoking the producer or authority under test."""
    spec = json.loads((package / SPEC).read_bytes())
    if rows is not None:
        spec["data_sources"] = copy.deepcopy(rows)
    (package / SPEC).write_bytes(json.dumps(spec, ensure_ascii=False).encode("utf-8"))
    raw = projection if isinstance(projection, bytes) else json.dumps(projection or LOCAL_PROJECTION).encode("utf-8")
    (package / PROJECTION).write_bytes(raw)
    manifest = json.loads((package / "package-manifest.json").read_bytes())
    manifest["artifacts"]["data_access"] = PROJECTION
    return seal(package, **manifest)


def filesystem_package(root: Path) -> Path:
    package = build_package(root, files={SPEC: "", PROJECTION: ""})
    (package / SPEC).write_bytes(b'{"data_sources":[]}\r\n')
    (package / PROJECTION).write_bytes(b'{"held":true}\r\n')
    write_manifest(package)
    return package


def require_held(value: object) -> pfs.HeldVerifiedMember:
    assert isinstance(value, pfs.HeldVerifiedMember), value
    return value


def require_handoff(value: object) -> pri.PackageDataAccessHandoff:
    assert isinstance(value, pri.PackageDataAccessHandoff), value
    return value


def assert_refusal(value: object, code: str) -> None:
    assert isinstance(value, pfs.PackageFilesystemResult), f"expected typed S1 refusal {code}, got {value!r}"
    assert value.first_code == code
    assert not value.is_clean
    assert all(row.path is None for row in (*value.findings, *value.unassessable))


@pytest.mark.parametrize("name", [SPEC, PROJECTION])
def test_s1_exact_member_bytes_and_digest_are_immutable(tmp_path: Path, name: str) -> None:
    package = filesystem_package(tmp_path)
    expected = (package / name).read_bytes()
    verified = verify(package)
    member = require_held(pfs.read_verified_member(package, verified, name))
    assert member.content == expected
    assert member.sha256 == hashlib.sha256(expected).hexdigest()
    assert member.relative_path == name and member.root_identity == str(package)
    assert type(member.content) is bytes  # pylint: disable=unidiomatic-typecheck
    assert type(verified.verified_files) is tuple  # pylint: disable=unidiomatic-typecheck
    with pytest.raises(AttributeError):
        member.content = b"replacement"
    with pytest.raises(AttributeError):
        verified.verified_files[0].sha256 = "0" * 64
    assert "verified_files" not in verified.as_dict() and "manifest" not in verified.as_dict()


def test_s1_holds_no_large_asset_bytes_and_reader_does_not_parse_manifest(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    package = filesystem_package(tmp_path)
    asset = package / "large.bin"
    with asset.open("wb") as handle:
        for _index in range(3):
            handle.write(b"asset" * (1 << 18))
    write_manifest(package)
    classification = classify(package)
    original = Path.read_bytes
    opened = []

    def read_once(path: Path) -> bytes:
        assert path != asset, "large assets must be streamed, not held in the S1 result"
        opened.append(path.name)
        return original(path)

    monkeypatch.setattr(Path, "read_bytes", read_once)
    verified = pfs.verify_package(package, classification)
    assert verified.is_clean
    assert opened == ["package-manifest.json"]
    assert all(
        not isinstance(getattr(member, field.name), bytes)
        for member in verified.verified_files
        for field in fields(member)
    )
    assert len(verified.manifest.content) < 4096

    def forbidden(*_args: object, **_kwargs: object) -> None:
        pytest.fail("a held member reader reparsed or rediscovered the manifest authority")

    monkeypatch.setattr(pfs, "parse_manifest_text", forbidden)
    monkeypatch.setattr(pfs, "declared_files", forbidden)
    member = require_held(pfs.read_verified_member(package, verified, PROJECTION))
    assert member.content == b'{"held":true}\r\n'
    assert opened == ["package-manifest.json", PROJECTION]


def test_held_member_rechecks_exact_s1_digest(tmp_path: Path) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)
    original = require_held(pfs.read_verified_member(package, verified, PROJECTION))
    path = package / PROJECTION
    before = path.stat()
    path.write_bytes(original.content.replace(b"true", b"null"))
    os.utime(path, ns=(before.st_atime_ns, before.st_mtime_ns))
    assert path.stat().st_size == before.st_size
    assert_refusal(pfs.read_verified_member(package, verified, PROJECTION), "package_file_digest_mismatch")


@pytest.mark.parametrize(
    "change,code",
    [
        ("deleted", "package_file_missing"),
        ("added", "package_file_undeclared"),
        ("manifest-digest", "package_file_digest_mismatch"),
        ("same-byte-replacement", "package_member_replaced"),
        ("hardlink", "package_member_replaced"),
        ("directory", "package_file_missing"),
        ("case-alias", "package_file_undeclared"),
    ],
)
def test_held_read_refuses_changed_namespace_or_identity(tmp_path: Path, change: str, code: str) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)
    path = package / PROJECTION
    if change == "deleted":
        path.unlink()
    elif change == "added":
        (package / "extra.bin").write_bytes(b"new")
    elif change == "manifest-digest":
        target = package / "package-manifest.json"
        target.write_bytes(target.read_bytes() + b"\n")
    elif change == "same-byte-replacement":
        raw = path.read_bytes()
        path.rename(tmp_path / "retired.bin")
        path.write_bytes(raw)
    elif change == "hardlink":
        os.link(path, tmp_path / "alias.bin")
    elif change == "directory":
        path.unlink()
        path.mkdir()
    else:
        path.rename(package / "renaming")
        (package / "renaming").rename(package / PROJECTION.upper())
    assert_refusal(pfs.read_verified_member(package, verified, PROJECTION), code)


def test_resealing_does_not_rebaseline_a_held_namespace(tmp_path: Path) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)
    (package / PROJECTION).write_bytes(b'{"new":true}')
    write_manifest(package)
    assert verify(package).is_clean, "the replacement is independently consistent, but not the held revision"
    assert_refusal(pfs.read_verified_member(package, verified, PROJECTION), "package_file_digest_mismatch")


def test_empty_directory_link_count_is_not_a_replaced_root(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)
    (package / "empty").mkdir()
    original = os.lstat

    def changed(path: Path, *args: object, **kwargs: object) -> os.stat_result:
        info = original(path, *args, **kwargs)
        if Path(path) != package:
            return info
        values = list(info)
        values[3] += 1
        extras = {key: getattr(info, key) for key in ("st_file_attributes", "st_reparse_tag") if hasattr(info, key)}
        return os.stat_result(values, extras)

    monkeypatch.setattr(os, "lstat", changed)
    assert require_held(pfs.read_verified_member(package, verified, PROJECTION)).content == b'{"held":true}\r\n'


@pytest.mark.parametrize("junction", [False, True])
def test_same_byte_replaced_root_never_reuses_s1(tmp_path: Path, junction: bool) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)
    retired = package.rename(tmp_path / "retired")
    if junction:
        link_directory(package, retired)
    else:
        shutil.copytree(retired, package)
    try:
        assert_refusal(pfs.read_verified_member(package, verified, PROJECTION), "package_root_replaced")
    finally:
        if junction:
            if os.name == "nt":
                package.rmdir()
            else:
                package.unlink()


def test_s1_root_identity_is_required_even_for_identical_bytes(tmp_path: Path) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)
    assert require_held(pfs.read_verified_member(package, verified, PROJECTION)).root_identity == str(package)
    foreign = replace(verified, root_identity=str(package).swapcase())
    assert_refusal(pfs.read_verified_member(package, foreign, PROJECTION), "package_root_binding_invalid")


@pytest.mark.parametrize("name", ["DATA-ACCESS.JSON", "./data-access.json", "data-access.json.", "../outside", None])
def test_only_exact_canonical_member_spelling_is_read(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, name: str | None
) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)

    def forbidden(*_args: object, **_kwargs: object) -> None:
        pytest.fail("an unverified spelling reached the filesystem")

    monkeypatch.setattr(pfs, "walk_package", forbidden)
    assert_refusal(pfs.read_verified_member(package, verified, name), "package_member_not_verified")


@pytest.mark.parametrize(
    "mode,code", [(stat.S_IFLNK, "package_entry_reparse"), (stat.S_IFCHR, "package_entry_not_regular")]
)
def test_reparse_and_nonregular_members_refuse_before_read(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, mode: int, code: str
) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)
    original = os.DirEntry.stat

    def changed(entry: os.DirEntry, *, follow_symlinks: bool = True) -> os.stat_result:
        info = original(entry, follow_symlinks=follow_symlinks)
        if entry.name != PROJECTION:
            return info
        values = list(info)
        values[0] = (info.st_mode & ~stat.S_IFMT(info.st_mode)) | mode
        extras = {key: getattr(info, key) for key in ("st_file_attributes", "st_reparse_tag") if hasattr(info, key)}
        return os.stat_result(values, extras)

    def forbidden(_path: Path) -> bytes:
        pytest.fail("a reparse/nonregular member was read")

    monkeypatch.setattr(os.DirEntry, "stat", changed)
    monkeypatch.setattr(Path, "read_bytes", forbidden)
    assert_refusal(pfs.read_verified_member(package, verified, PROJECTION), code)


def test_case_colliding_manifest_cannot_publish_a_verified_namespace(tmp_path: Path) -> None:
    package = filesystem_package(tmp_path)
    hashes = {name: hashlib.sha256((package / name).read_bytes()).hexdigest() for name in (SPEC, PROJECTION)}
    write_manifest(package, files={**hashes, PROJECTION.upper(): hashes[PROJECTION]})
    result = verify(package)
    assert result.first_code == "package_declared_keys_collide"
    assert (result.verified_files, result.manifest) == ((), None)


def test_unreadable_member_returns_only_fixed_s1_diagnostics(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)

    def denied(_path: Path) -> bytes:
        raise PermissionError("PRIVATE endpoint source-name audit path credential")

    monkeypatch.setattr(Path, "read_bytes", denied)
    result = pfs.read_verified_member(package, verified, PROJECTION)
    assert_refusal(result, "package_file_unreadable")
    assert result.status == "unassessable"
    serialized = json.dumps(result.as_dict())
    assert "PRIVATE" not in serialized and str(package) not in serialized and '"path"' not in serialized


def test_s2_handoff_carries_current_live_keys(tmp_path: Path) -> None:
    package = with_data_access(
        datasource_package(tmp_path / "Source", luid=None), source_rows(OTHER, LIVE), LIVE_PROJECTION
    )
    result = pri.verify_phase1_role_identity([package])[0]
    assert result.is_start_ready, result.codes()
    handoff = require_handoff(result.data_access_handoff(package))
    assert handoff.facts.live_source_keys == (LIVE_KEY, OTHER_KEY), "the current live-key handoff was lost"
    assert handoff.facts.direct_applicable and not handoff.facts.all_flat
    assert not handoff.facts.has_review and handoff.facts.refusal_code is None
    assert handoff.migration_spec.content == (package / SPEC).read_bytes()
    assert handoff.data_access.content == (package / PROJECTION).read_bytes()
    assert handoff.migration_spec.root_identity == handoff.data_access.root_identity == str(package)
    assert handoff.migration_spec.sha256 == hashlib.sha256(handoff.migration_spec.content).hexdigest()
    assert handoff.data_access.sha256 == hashlib.sha256(handoff.data_access.content).hexdigest()


def test_s2_spec_is_parsed_once_and_only_the_authority_walks(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source", luid=None), source_rows(LIVE), LIVE_PROJECTION)
    original_read, original_walk, derive = Path.read_bytes, pfs._walk_package, pri.package_spec_facts
    reads, inputs = [], []

    def recorded(path: Path) -> bytes:
        if path.name == SPEC:
            reads.append(path)
        return original_read(path)

    def walked(root: Path):
        assert inspect.currentframe().f_back.f_globals["__name__"] == "package_filesystem", "consumer rewalked S1"
        return original_walk(root)

    def facts(spec: object) -> gate.PackageSpecFacts:
        inputs.append(copy.deepcopy(spec))
        return derive(spec)

    monkeypatch.setattr(Path, "read_bytes", recorded)
    monkeypatch.setattr(pfs, "_walk_package", walked)
    monkeypatch.setattr(pri, "package_spec_facts", facts)
    result = pri.verify_phase1_role_identity([package])[0]
    assert result.is_start_ready, result.codes()
    assert reads == [package / SPEC] and len(inputs) == 1
    assert inputs[0]["data_sources"] == source_rows(LIVE)
    handoff = require_handoff(result.data_access_handoff(package))
    assert reads == [package / SPEC, package / SPEC] and len(inputs) == 1, (
        "freshness recheck reparsed/reclassified the spec"
    )
    assert handoff.facts.live_source_keys == (LIVE_KEY,)


@pytest.mark.parametrize(
    "projection", [LIVE_PROJECTION, {**LIVE_PROJECTION, "source_keys": [OTHER_KEY]}, LOCAL_PROJECTION]
)
def test_projection_discrimination_needs_only_new_handoffs(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, projection: dict
) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source", luid=None), source_rows(LIVE), projection)
    result = pri.verify_phase1_role_identity([package])[0]
    assert result.is_start_ready

    def forbidden(*_args: object, **_kwargs: object) -> None:
        pytest.fail("a held handoff read audit, reprobed, reclassified or reparsed the manifest")

    for name in (
        "_read_audit_trail",
        "_audit_entries",
        "assess_data_access",
        "read_data_access",
        "_classify_legs",
        "load_bundle",
    ):
        monkeypatch.setattr(gate, name, forbidden)
    monkeypatch.setattr(pri, "package_spec_facts", forbidden)
    monkeypatch.setattr(pfs, "parse_manifest_text", forbidden)
    monkeypatch.setattr(pfs, "declared_files", forbidden)
    handoff = require_handoff(result.data_access_handoff(package))
    parsed = gate.parse_data_access(handoff.data_access.content.decode("utf-8"))
    assert parsed.state == projection["state"], "the existing projection parser must still accept every control"
    assert handoff.facts.live_source_keys == (LIVE_KEY,)
    assert (parsed.source_keys == handoff.facts.live_source_keys) is (projection == LIVE_PROJECTION)
    assert handoff.facts.all_flat is False, "local-over-live must be distinguishable without reclassification"


@pytest.mark.parametrize("change", ["target", "case", "verified", "snapshot"])
def test_s2_snapshot_cannot_borrow_another_package(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, change: str
) -> None:
    first = with_data_access(datasource_package(tmp_path / "First", luid=None), source_rows(LIVE), LIVE_PROJECTION)
    second = with_data_access(datasource_package(tmp_path / "Second", luid=None), source_rows(FLAT))
    result, other = pri.verify_phase1_role_identity([first, second])
    target = first
    if change == "target":
        target = second
    elif change == "case":
        target = Path(str(first).swapcase())
    elif change == "verified":
        result = replace(result, verified=other.verified)
    else:
        result = replace(result, _data_access_snapshot=other._data_access_snapshot)

    def forbidden(*_args: object, **_kwargs: object) -> None:
        pytest.fail("a cross-root S2 handoff reached an S1 read")

    monkeypatch.setattr(pfs, "read_verified_member", forbidden)
    assert_refusal(result.data_access_handoff(target), "package_root_binding_invalid")


@pytest.mark.parametrize("declaration", [None, False, [], "DATA-ACCESS.JSON", "./data-access.json", "other.json"])
def test_s2_never_discovers_an_undeclared_projection(tmp_path: Path, declaration: object) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(FLAT))
    manifest = json.loads((package / "package-manifest.json").read_bytes())
    manifest["artifacts"]["data_access"] = declaration
    seal(package, **manifest)
    result = pri.verify_phase1_role_identity([package])[0]
    assert result.is_start_ready, "this PR must not add the final data-access role/fold to S2"
    assert_refusal(result.data_access_handoff(package), "package_member_not_verified")


@pytest.mark.parametrize("name", [SPEC, PROJECTION])
def test_post_s2_changes_refuse_instead_of_mixing_snapshots(tmp_path: Path, name: str) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(LIVE), LIVE_PROJECTION)
    result = pri.verify_phase1_role_identity([package])[0]
    path = package / name
    path.write_bytes(path.read_bytes() + b"\n")
    assert_refusal(result.data_access_handoff(package), "package_file_digest_mismatch")


@pytest.mark.parametrize("reverse", [False, True])
def test_provider_ordinals_and_owned_roles_keep_exact_snapshot_roots(tmp_path: Path, reverse: bool) -> None:
    first = with_data_access(
        datasource_package(tmp_path / "first", unit="Shared", luid=DS_LUID), source_rows(LIVE), LIVE_PROJECTION
    )
    second = with_data_access(datasource_package(tmp_path / "second", unit="Shared", luid=WB_LUID), source_rows(FLAT))
    consumer = with_data_access(
        workbook_package(
            tmp_path / "Consumer", published={"luid": DS_LUID}, binding="../../../first/fabric/Shared.SemanticModel"
        ),
        [{**PUBLISHED, "published_datasource": {"luid": DS_LUID}}],
    )
    owned = with_data_access(workbook_package(tmp_path / "Owned", unit="Owned"), source_rows(FLAT))
    roots = [first, second, consumer, owned]
    if reverse:
        roots.reverse()
    observations = tuple(pri.verify_s1(root) for root in reversed(roots))
    results = pri.verify_phase1_role_identity(roots, verified=observations)
    assert all(result.is_start_ready for result in results)
    for root, result in zip(roots, results, strict=True):
        held = require_handoff(result.data_access_handoff(root))
        assert held.migration_spec.root_identity == held.data_access.root_identity == str(root)
        assert held.migration_spec.content == (root / SPEC).read_bytes()
    provider, consuming, own = (results[roots.index(root)] for root in (first, consumer, owned))
    assert provider.topology == "published_provider" and own.topology == "owned_model"
    assert consuming.dependencies[0].provider_ordinal == roots.index(first)
    assert consuming.dependencies[0].provider_unit == "Shared"
    assert consuming.brief_policy.requested_scope == "report_only_shared_model"
    assert require_handoff(consuming.data_access_handoff(consumer)).facts.published_only
    assert own.source_handoff().root_identity == str(owned), "the existing package_source API must not change"


@pytest.mark.parametrize(
    "connections,keys,review,refusal",
    [
        ([FLAT], (), False, None),
        ([LIVE], (LIVE_KEY,), False, None),
        ([OTHER, LIVE], (LIVE_KEY, OTHER_KEY), False, None),
        ([REVIEW], (), True, None),
        ([LIVE, REVIEW], (LIVE_KEY,), True, None),
        ([LIVE, LIVE], (), False, "source-key-invalid"),
        ([{"class": "sqlserver", "powerbi_target": "live_source"}], (), False, "source-key-invalid"),
        ([{**LIVE, "server": True}], (), False, "spec-unreadable"),
        ([{**LIVE, "connections": "malformed"}], (), False, "spec-unreadable"),
    ],
)
def test_pure_spec_facts_reuse_canonical_leg_derivation(
    connections: list[dict], keys: tuple[str, ...], review: bool, refusal: str | None
) -> None:
    spec = {"data_sources": source_rows(*connections)}
    original = copy.deepcopy(spec)
    facts = gate.package_spec_facts(spec)
    assert (facts.live_source_keys, facts.has_review, facts.refusal_code) == (keys, review, refusal)
    assert facts.all_flat is (connections == [FLAT])
    assert not facts.published_only
    assert spec == original
    with pytest.raises(AttributeError):
        facts.has_review = False


@pytest.mark.parametrize("rows", [None, {}, False, "rows", [None], [False], [{"connection": []}], [{"fields": False}]])
def test_malformed_source_sets_preserve_authority_refusal(rows: object) -> None:
    facts = gate.package_spec_facts({"data_sources": rows})
    assert facts.refusal_code == "spec-unreadable"
    assert facts.live_source_keys == () and not facts.all_flat and not facts.published_only


def test_mixed_published_rows_are_not_published_only() -> None:
    published = gate.package_spec_facts({"data_sources": [copy.deepcopy(PUBLISHED)]})
    mixed = gate.package_spec_facts({"data_sources": [copy.deepcopy(PUBLISHED), *source_rows(LIVE)]})
    assert published.published_only and not published.direct_applicable
    assert published.live_source_keys == () and published.refusal_code is None
    assert not mixed.published_only, "a mixed-row handoff would let the future consumer borrow provider-only proof"
    assert not mixed.direct_applicable and not mixed.all_flat
    assert mixed.live_source_keys == (LIVE_KEY,)


@pytest.mark.parametrize(
    "extra",
    [
        {"connection": {**PUBLISHED["connection"], "connections": [LIVE]}},
        {"connection": {**PUBLISHED["connection"], "connections": []}},
        {"connection": {**PUBLISHED["connection"], "unknown": "sqlserver"}},
        {"connection": {**PUBLISHED["connection"], "mode": True}},
        {"connection": {"class": "SQLPROXY", "mode": "live"}},
        {"connections": [LIVE]},
        {"tables": [{"connection": LIVE}]},
        {"fields": [{"nested": {"connections": [LIVE]}}]},
        {"joins": [{"right": {"class": "sqlserver"}}]},
        {"fields": False},
        {"id": False},
        {"caption": []},
        {"published_datasource": {"luid": DS_LUID, "connection": LIVE}},
        {"published_datasource": {"luid": True}},
        {"published_datasource": None},
    ],
)
def test_malformed_or_nested_published_rows_never_gain_clean_applicability(extra: dict) -> None:
    facts = gate.package_spec_facts({"data_sources": [{**PUBLISHED, **extra}]})
    assert not facts.published_only and not facts.direct_applicable and not facts.all_flat


@pytest.mark.parametrize("raw", [b'{"source":{},"source":{}}', b'{"x":NaN}', b'{"x":1e999}', b"[]", b"\xff"])
def test_strict_spec_json_still_blocks_at_s2(tmp_path: Path, raw: bytes) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(LIVE), LIVE_PROJECTION)
    (package / SPEC).write_bytes(raw)
    seal(package, **json.loads((package / "package-manifest.json").read_bytes()))
    result = pri.verify_phase1_role_identity([package])[0]
    assert "identity_json_invalid" in result.blockers
    assert not result.is_start_ready
    assert_refusal(result.data_access_handoff(package), "package_member_not_verified")


@pytest.mark.parametrize(
    "raw,reason", [(b'{"state":0,"state":1}', "duplicate-key"), (b'{"x":NaN}', "nonfinite"), (b"[]", "not-an-object")]
)
def test_projection_stays_held_and_existing_parser_owns_strictness(tmp_path: Path, raw: bytes, reason: str) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(FLAT), raw)
    result = pri.verify_phase1_role_identity([package])[0]
    held = require_handoff(result.data_access_handoff(package))
    assert result.is_start_ready and held.data_access.content == raw, "no semantic consumer belongs in this PR"
    with pytest.raises(gate.DataAccessProjectionError) as caught:
        gate.parse_data_access(held.data_access.content.decode("utf-8"))
    assert caught.value.reason == reason


def test_new_handoffs_add_no_serialized_private_diagnostics(tmp_path: Path) -> None:
    private = {**LIVE, "server": "private-endpoint.example", "database": "private-database"}
    package = with_data_access(
        datasource_package(tmp_path / "PrivateRoot", luid=None), source_rows(private), LIVE_PROJECTION
    )
    result = pri.verify_phase1_role_identity([package])[0]
    handoff = require_handoff(result.data_access_handoff(package))
    assert set(result.as_dict()) == {
        "verdict",
        "unit",
        "kind",
        "topology",
        "roles",
        "source_identity",
        "dependencies",
        "blockers",
        "authorized_limitations",
    }
    serialized = json.dumps(result.as_dict()) + json.dumps(result.verified.integrity.as_dict()) + repr(handoff)
    for forbidden in (
        "private-endpoint",
        "private-database",
        "PrivateRoot",
        "data_sources",
        ".credential-gate",
    ):
        assert forbidden not in serialized
    assert str(tmp_path) not in serialized and repr(handoff.migration_spec.content) not in serialized


def rebuild_result(value: object) -> object:
    """Reconstruct every constructor field, without assuming knowledge of a private capability."""
    return type(value)(**{field.name: getattr(value, field.name) for field in fields(value) if field.init})


@pytest.mark.parametrize("mode", ["copy", "deepcopy", "replace", "rebuild", "findings", "unassessable", "counts"])
def test_r1_s1_requires_its_original_verification(tmp_path: Path, mode: str) -> None:
    package = filesystem_package(tmp_path)
    original = verify(package)
    assert require_held(pfs.read_verified_member(package, original, PROJECTION)).relative_path == PROJECTION
    copies = {"copy": copy.copy, "deepcopy": copy.deepcopy, "replace": replace, "rebuild": rebuild_result}
    if mode in copies:
        supplied = copies[mode](original)
    elif mode == "counts":
        supplied = replace(original, files_verified=0)
    else:
        row = pfs.Finding("package_file_digest_mismatch", "R1_PRIVATE_DIAGNOSTIC", path="R1_PRIVATE_PATH")
        supplied = replace(original, **{mode: (row,)})
    result = pfs.read_verified_member(package, supplied, PROJECTION)
    assert isinstance(result, pfs.PackageFilesystemResult), f"S1 {mode} minted held bytes without original authority"
    assert result.first_code == "package_member_not_verified"
    assert "R1_PRIVATE" not in json.dumps(result.as_dict())


def test_r1_s1_rejects_contradictory_original_state(tmp_path: Path) -> None:
    package = filesystem_package(tmp_path)
    original = verify(package)
    assert require_held(pfs.read_verified_member(package, original, PROJECTION)).relative_path == PROJECTION
    object.__setattr__(original, "files_verified", 0)
    result = pfs.read_verified_member(package, original, PROJECTION)
    assert isinstance(result, pfs.PackageFilesystemResult), "contradictory original S1 state minted held bytes"
    assert result.first_code == "package_member_not_verified"


@pytest.mark.parametrize(
    "mode", ["copy", "deepcopy", "replace", "rebuild", "snapshot", "content", "facts", "blockers", "role"]
)
def test_r1_s2_requires_its_original_role_result(tmp_path: Path, mode: str) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(LIVE), LIVE_PROJECTION)
    original = pri.verify_phase1_role_identity([package])[0]
    require_handoff(original.data_access_handoff(package))
    snapshot = original._data_access_snapshot
    copies = {"copy": copy.copy, "deepcopy": copy.deepcopy, "replace": replace, "rebuild": rebuild_result}
    if mode in copies:
        supplied = copies[mode](original)
    elif mode in ("snapshot", "content", "facts"):
        altered = rebuild_result(snapshot)
        if mode == "content":
            altered = replace(altered, spec=replace(altered.spec, content=b'{"R1_PRIVATE_SPEC":"forged"}'))
        elif mode == "facts":
            altered = replace(altered, facts=altered.facts._replace(live_source_keys=()))
        supplied = replace(original, _data_access_snapshot=altered)
    elif mode == "blockers":
        supplied = replace(original, blockers=("R1_PRIVATE_BLOCKER",))
    else:
        altered_roles = tuple(
            replace(role, state="missing", code="R1_PRIVATE_ROLE") if role.role == pri.ROLE_MIGRATION_SPEC else role
            for role in original.roles
        )
        supplied = replace(original, roles=altered_roles)
    result = supplied.data_access_handoff(package)
    assert isinstance(result, pfs.PackageFilesystemResult), f"S2 {mode} returned an unissued or forged handoff"
    assert "R1_PRIVATE" not in json.dumps(result.as_dict())


@pytest.mark.parametrize("field", ["content", "facts", "blockers", "role", "snapshot"])
def test_r1_s2_checks_original_handoff_consistency(tmp_path: Path, field: str) -> None:
    """Change one field in place to exercise consistency separately from copied-result rejection."""
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(LIVE), LIVE_PROJECTION)
    original = pri.verify_phase1_role_identity([package])[0]
    require_handoff(original.data_access_handoff(package))
    snapshot = original._data_access_snapshot
    if field == "content":
        object.__setattr__(snapshot.spec, "content", b'{"R1_PRIVATE_SPEC":"forged"}')
    elif field == "facts":
        object.__setattr__(snapshot, "facts", snapshot.facts._replace(live_source_keys=()))
    elif field == "blockers":
        object.__setattr__(original, "blockers", ("R1_PRIVATE_BLOCKER",))
    elif field == "role":
        role = next(role for role in original.roles if role.role == pri.ROLE_MIGRATION_SPEC)
        object.__setattr__(role, "state", "missing")
    else:
        object.__setattr__(original, "_data_access_snapshot", rebuild_result(snapshot))
    result = original.data_access_handoff(package)
    assert isinstance(result, pfs.PackageFilesystemResult), (
        f"S2 original {field} inconsistency returned forged authority"
    )
    if field == "content":
        assert result.first_code == "package_file_digest_mismatch"
    assert "R1_PRIVATE" not in json.dumps(result.as_dict())


def test_r1_blocked_s2_cannot_be_reconstructed_as_ready(tmp_path: Path) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(LIVE), LIVE_PROJECTION)
    (package / "migration-brief.md").write_bytes(b"+++\n")
    seal(package, **json.loads((package / "package-manifest.json").read_bytes()))
    blocked = pri.verify_phase1_role_identity([package])[0]
    assert not blocked.is_start_ready and blocked.blockers
    supplied = replace(
        blocked,
        verdict="START_READY",
        blockers=(),
        roles=tuple(replace(role, state="resolved", code=None) for role in blocked.roles),
    )
    result = supplied.data_access_handoff(package)
    assert isinstance(result, pfs.PackageFilesystemResult), "reconstructed S2 readiness manufactured a handoff"


@pytest.mark.parametrize("target", ["live_source", "unknown"])
def test_r1_sqlproxy_cohort_retains_canonical_direct_or_review_leg(tmp_path: Path, target: str) -> None:
    provider = with_data_access(
        datasource_package(tmp_path / "Provider", unit="Shared", luid=DS_LUID), source_rows(FLAT)
    )
    connection = {
        "class": "sqlproxy",
        "mode": "live",
        "server": "direct.example",
        "database": "db",
        "powerbi_target": target,
    }
    consumer = with_data_access(
        workbook_package(
            tmp_path / "Consumer",
            published={"luid": DS_LUID},
            binding="../../../Provider/fabric/Shared.SemanticModel",
        ),
        [{"connection": connection, "published_datasource": {"luid": DS_LUID}}],
    )
    results = pri.verify_phase1_role_identity([provider, consumer])
    assert all(result.is_start_ready for result in results)
    assert results[1].dependencies[0].provider_ordinal == 0
    facts = require_handoff(results[1].data_access_handoff(consumer)).facts
    endpoint = {"class": "sqlproxy", "server": "direct.example", "database": "db", "schema": ""}
    key = (
        "source-key:"
        + hashlib.sha256(json.dumps(endpoint, sort_keys=True, separators=(",", ":")).encode("utf-8")).hexdigest()[:16]
    )
    assert facts.live_source_keys == ((key,) if target == "live_source" else ()), (
        "sqlproxy's canonical live key was stripped"
    )
    assert facts.has_review is (target == "unknown"), "sqlproxy's canonical review leg was stripped"
    assert facts.refusal_code is None
    assert not facts.published_only, "a provider-shaped direct/review leg was granted published-only applicability"


@pytest.mark.parametrize("surface", ["s1", "s2"])
def test_r1_small_metadata_never_rehashes_unrelated_eight_mib_asset(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, surface: str
) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(FLAT))
    unrelated = package / "data" / "large.bin"
    unrelated.parent.mkdir()
    unrelated.write_bytes(b"Z" * (8 << 20))
    seal(package, **json.loads((package / "package-manifest.json").read_bytes()))
    role_result = pri.verify_phase1_role_identity([package])[0]
    assert role_result.is_start_ready
    original_hash, original_read = pfs._hash_file, Path.read_bytes
    hashed, held = [], []

    def tracked_hash(path: Path) -> str | None:
        hashed.append(path)
        return original_hash(path)

    def tracked_read(path: Path) -> bytes:
        held.append(path)
        return original_read(path)

    monkeypatch.setattr(pfs, "_hash_file", tracked_hash)
    monkeypatch.setattr(Path, "read_bytes", tracked_read)
    if surface == "s1":
        for name in (SPEC, PROJECTION):
            require_held(role_result.verified.read_verified_member(package, name))
    else:
        require_handoff(role_result.data_access_handoff(package))
    assert unrelated not in hashed, f"{surface} small metadata access rehashed the unrelated 8 MiB asset"
    assert unrelated not in held, f"{surface} small metadata access retained unrelated asset bytes"


def test_r1_unclassified_sqlproxy_cannot_claim_published_only() -> None:
    row = copy.deepcopy(PUBLISHED)
    del row["connection"]["powerbi_target"]
    facts = gate.package_spec_facts({"data_sources": [row]})
    assert facts.refusal_code == "source-key-invalid"
    assert not facts.published_only, "published shape cannot repair canonical uncertainty"


def test_r1_member_read_does_not_claim_fresh_integrity_for_unrelated_content(tmp_path: Path) -> None:
    """A bounded member read is not a new whole-package verification."""
    package = filesystem_package(tmp_path)
    original = verify(package)
    (package / SPEC).write_bytes(b"unrelated changed content")
    assert require_held(pfs.read_verified_member(package, original, PROJECTION)).content == b'{"held":true}\r\n'
    assert verify(package).first_code == "package_file_digest_mismatch"


@pytest.mark.parametrize(
    "member,field,value",
    [
        ("source_identity", "kind", "workbook"),
        ("source_identity", "sha256", "0" * 64),
        ("source_identity", "tableau_luid", WB_LUID),
        ("source_identity", "published_key", "HANDOFF_PRIVATE_KEY"),
        ("source_identity", "revision", "HANDOFF_PRIVATE_REVISION"),
        ("brief_policy", "requested_scope", "model_and_report"),
        ("brief_policy", "fallback_authorization", "model_only_unvalidated"),
    ],
)
def test_issued_s2_binds_each_source_and_brief_scalar(tmp_path: Path, member: str, field: str, value: str) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(LIVE), LIVE_PROJECTION)
    original = pri.verify_phase1_role_identity([package])[0]
    require_handoff(original.data_access_handoff(package))
    component = getattr(original, member)
    assert getattr(component, field) != value
    object.__setattr__(component, field, value)
    assert getattr(original, member) is component and original.is_start_ready
    refused = original.data_access_handoff(package)
    assert_refusal(refused, "package_member_not_verified")
    assert "HANDOFF_PRIVATE" not in json.dumps(refused.as_dict())


def test_issued_s2_preserves_absent_brief_policy(tmp_path: Path) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source", luid=None), source_rows(FLAT))
    (package / "migration-brief.md").write_text("Migrate it.\n", encoding="utf-8")
    seal(package, **json.loads((package / "package-manifest.json").read_bytes()))
    original = pri.verify_phase1_role_identity([package])[0]
    assert original.is_start_ready and original.brief_policy is None
    assert (original.source_identity.tableau_luid, original.source_identity.published_key) == (None, None)
    assert require_handoff(original.data_access_handoff(package)).facts.all_flat
    object.__setattr__(original, "brief_policy", pri.BriefPolicy("model_only", "stop"))
    assert_refusal(original.data_access_handoff(package), "package_member_not_verified")


def test_fresh_s1_cannot_renew_stale_s2_by_grafting_both_integrity_references(tmp_path: Path) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(LIVE), LIVE_PROJECTION)
    stale = pri.verify_phase1_role_identity([package])[0]
    held = require_handoff(stale.data_access_handoff(package))
    wrapper, snapshot = stale.verified, stale._data_access_snapshot
    issued_integrity = wrapper.integrity
    brief = package / "migration-brief.md"
    before = brief.read_bytes()
    after = before.replace(b'fallback_authorization = "stop"', b'fallback_authorization = "model_only_unvalidated"')
    assert after != before
    brief.write_bytes(after)
    seal(package, **json.loads((package / "package-manifest.json").read_bytes()))
    fresh_s1 = pri.verify_s1(package)
    assert fresh_s1.integrity.is_clean and fresh_s1.integrity.has_read_authority()
    assert fresh_s1.integrity is not issued_integrity
    assert require_held(fresh_s1.read_verified_member(package, SPEC)).content == held.migration_spec.content
    assert require_held(fresh_s1.read_verified_member(package, PROJECTION)).content == held.data_access.content
    object.__setattr__(wrapper, "integrity", fresh_s1.integrity)
    object.__setattr__(snapshot, "integrity", fresh_s1.integrity)
    assert stale.verified is wrapper and stale._data_access_snapshot is snapshot
    assert stale.brief_policy.fallback_authorization == "stop"
    assert_refusal(stale.data_access_handoff(package), "package_member_not_verified")

    renewed = pri.verify_phase1_role_identity([package], verified=[fresh_s1])[0]
    assert renewed.is_start_ready and renewed.brief_policy.fallback_authorization == "model_only_unvalidated"
    assert renewed.verified.integrity is not fresh_s1.integrity
    assert require_handoff(renewed.data_access_handoff(package)).facts.live_source_keys == (LIVE_KEY,)


def test_issued_s2_requires_its_integrity_to_retain_read_authority(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(FLAT))
    original = pri.verify_phase1_role_identity([package])[0]
    require_handoff(original.data_access_handoff(package))
    integrity = original.verified.integrity
    object.__setattr__(integrity, "files_verified", 0)
    assert original._data_access_snapshot.integrity is integrity and not integrity.has_read_authority()

    def forbidden(*_args: object, **_kwargs: object) -> None:
        pytest.fail("an S2 capability with inconsistent issuing S1 authority reached a member read")

    monkeypatch.setattr(pfs, "read_verified_member", forbidden)
    assert_refusal(original.data_access_handoff(package), "package_member_not_verified")


@pytest.mark.parametrize("connection,keys,all_flat", [(FLAT, (), True), (LIVE, (LIVE_KEY,), False)])
@pytest.mark.parametrize("selected", [False, True])
def test_published_provider_applicability_uses_final_cohort_topology(
    tmp_path: Path, connection: dict, keys: tuple[str, ...], all_flat: bool, selected: bool
) -> None:
    rows = [{**source_rows(connection)[0], "published_datasource": {"luid": DS_LUID, "key": PUBLISHED_KEY}}]
    provider = with_data_access(
        datasource_package(tmp_path / "Provider", unit="Shared", published_key=PUBLISHED_KEY), rows
    )
    roots = [provider]
    if selected:
        roots.append(
            with_data_access(
                workbook_package(
                    tmp_path / "Consumer",
                    published={"luid": DS_LUID, "key": PUBLISHED_KEY},
                    binding="../../../Provider/fabric/Shared.SemanticModel",
                ),
                [PUBLISHED],
            )
        )
    canonical = gate.package_spec_facts({"data_sources": rows})
    assert tuple(canonical) == (keys, False, False, False, None), "the one-argument canonical API must not change"
    results = pri.verify_phase1_role_identity(roots)
    assert all(result.is_start_ready for result in results)
    provider_result = results[0]
    assert provider_result.topology == ("published_provider" if selected else "standalone_datasource")
    assert provider_result.source_identity.published_key == PUBLISHED_KEY
    facts = require_handoff(provider_result.data_access_handoff(provider)).facts
    assert tuple(facts) == (keys, False, True, False, None)
    assert facts.all_flat is all_flat
    if selected:
        assert results[1].topology == "published_consumer" and results[1].dependencies[0].provider_ordinal == 0


@pytest.mark.parametrize("publication_metadata", [False, True])
@pytest.mark.parametrize("selected", [False, True])
def test_mixed_case_sqlproxy_retains_canonical_direct_applicability(
    tmp_path: Path, publication_metadata: bool, selected: bool
) -> None:
    rows = source_rows({**PUBLISHED["connection"], "class": "SQLPROXY"})
    if publication_metadata:
        rows[0]["published_datasource"] = {"luid": DS_LUID, "key": PUBLISHED_KEY}
    canonical = gate.package_spec_facts({"data_sources": rows})
    assert tuple(canonical) == ((), False, not publication_metadata, False, None)
    assert canonical.all_flat is (not publication_metadata)
    provider = with_data_access(datasource_package(tmp_path / "Provider", unit="Shared"), rows)
    roots = [provider]
    if selected:
        roots.append(
            with_data_access(
                workbook_package(
                    tmp_path / "Consumer",
                    published={"luid": DS_LUID, "key": PUBLISHED_KEY},
                    binding="../../../Provider/fabric/Shared.SemanticModel",
                ),
                [PUBLISHED],
            )
        )
    results = pri.verify_phase1_role_identity(roots)
    assert all(result.is_start_ready for result in results)
    assert results[0].topology == ("published_provider" if selected else "standalone_datasource")
    facts = require_handoff(results[0].data_access_handoff(provider)).facts
    assert tuple(facts) == ((), False, True, False, None)
    assert facts.all_flat
    if selected:
        assert results[1].topology == "published_consumer" and results[1].dependencies[0].provider_ordinal == 0
        assert require_handoff(results[1].data_access_handoff(roots[1])).facts.published_only


@pytest.mark.parametrize(
    "additional,keys,review",
    [(None, (), False), (LIVE, (LIVE_KEY,), False), (REVIEW, (), True)],
)
def test_consumer_applicability_preserves_strict_proxy_and_mixed_canonical_facts(
    tmp_path: Path, additional: dict | None, keys: tuple[str, ...], review: bool
) -> None:
    provider = with_data_access(datasource_package(tmp_path / "Provider", unit="Shared"), source_rows(FLAT))
    rows = [PUBLISHED, *(source_rows(additional) if additional is not None else [])]
    consumer = with_data_access(
        workbook_package(
            tmp_path / "Consumer",
            published={"luid": DS_LUID, "key": PUBLISHED_KEY},
            binding="../../../Provider/fabric/Shared.SemanticModel",
        ),
        rows,
    )
    canonical = gate.package_spec_facts({"data_sources": rows})
    assert tuple(canonical) == (keys, review, False, additional is None, None)
    results = pri.verify_phase1_role_identity([provider, consumer])
    assert all(result.is_start_ready for result in results)
    assert results[0].topology == "published_provider" and results[1].topology == "published_consumer"
    facts = require_handoff(results[1].data_access_handoff(consumer)).facts
    assert tuple(facts) == (keys, review, False, additional is None, None)
    assert not facts.all_flat


def test_datasource_proxy_cannot_borrow_consumer_applicability(tmp_path: Path) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), [PUBLISHED])
    assert tuple(gate.package_spec_facts({"data_sources": [PUBLISHED]})) == ((), False, False, True, None)
    result = pri.verify_phase1_role_identity([package])[0]
    assert result.is_start_ready and result.topology == "standalone_datasource"
    facts = require_handoff(result.data_access_handoff(package)).facts
    assert tuple(facts) == ((), False, False, False, None)
    assert not facts.all_flat


def test_handoff_consistency_refusal_preserves_private_policy_and_public_shapes(tmp_path: Path) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source", luid=None), source_rows(LIVE), LIVE_PROJECTION)
    result = pri.verify_phase1_role_identity([package])[0]
    handoff = require_handoff(result.data_access_handoff(package))
    public_role, public_integrity = result.as_dict(), result.verified.integrity.as_dict()
    assert set(public_role["source_identity"]) == {"kind", "sha256", "tableau_luid", "published_key"}
    assert set(public_integrity) == {"status", "files_declared", "files_verified", "findings", "unassessable"}
    assert tuple(field.name for field in fields(handoff)) == ("migration_spec", "facts", "data_access")
    assert handoff.facts._fields == (
        "live_source_keys",
        "has_review",
        "direct_applicable",
        "published_only",
        "refusal_code",
    )
    object.__setattr__(result.brief_policy, "fallback_authorization", "HANDOFF_PRIVATE credential endpoint")
    refused = result.data_access_handoff(package)
    assert_refusal(refused, "package_member_not_verified")
    assert result.as_dict() == public_role and result.verified.integrity.as_dict() == public_integrity
    assert set(refused.as_dict()) == set(public_integrity)
    assert set(refused.as_dict()["findings"][0]) == {"code", "detail"}
    serialized = json.dumps(refused.as_dict())
    assert "HANDOFF_PRIVATE" not in serialized and str(package) not in serialized
