"""Tests for scripts/build_synthetic_reference.py — the honestly-labeled synthetic reference chart.

Built to unblock agents that kept asking for a missing Tableau reference image during the
credential-gate model-matrix testing (the _probe-lab/ fixtures have no real Tableau dashboard to
screenshot — the .twb is a synthetic skeleton generated by probe_lab.py). The one property every
test here protects is honesty: nothing produced by this script may be mistaken for a real capture
(see docs/reference-capture.md's "validation_grade" contract), and it must never silently clobber a
real one.
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "scripts"))

# ruff: noqa: E402  (the sys.path insert above must precede these imports)
import build_synthetic_reference as bsr


def _fake_png(path: Path, width: int = 900, height: int = 400) -> None:
    """Write a minimal-but-valid PNG (per _png_dimensions/_is_valid_png) padded past the size floor.

    _is_valid_png only checks file size (>20000 bytes) and that the first 24 bytes parse as a PNG
    IHDR chunk — it never decodes pixels — so a real Chromium screenshot is not needed to exercise
    the manifest-writing logic these tests target.
    """
    header = b"\x89PNG\r\n\x1a\n" + struct.pack(">I", 13) + b"IHDR" + struct.pack(">II", width, height)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(header + b"\x00" * 21000)


@pytest.fixture(autouse=True)
def _stub_screenshot(monkeypatch: pytest.MonkeyPatch) -> None:
    """Replace the real Playwright/node capture with a fake-PNG writer in every test in this file."""

    def _fake_screenshot(_html: str, out_path: Path) -> bool:
        _fake_png(out_path)
        return True

    monkeypatch.setattr(bsr, "screenshot_html", _fake_screenshot)


def _rows_file(tmp_path: Path, rows: list[dict]) -> Path:
    path = tmp_path / "rows.json"
    path.write_text(json.dumps(rows), encoding="utf-8")
    return path


REAL_ROWS = [
    {"label": "Northwind Traders", "value": 323450.02},
    {"label": "Litware Inc", "value": 196466.72},
    {"label": "Contoso Ltd", "value": 237711.08},
]


def test_render_html_sorts_descending_and_embeds_disclaimer() -> None:
    """The chart must sort by value descending and always carry the baked-in disclaimer text."""
    html = bsr.render_html("Billing by Customer", "Overview", REAL_ROWS, "$")
    assert bsr.DISCLAIMER in html
    first = html.index("Northwind Traders")
    second = html.index("Contoso Ltd")
    third = html.index("Litware Inc")
    assert first < second < third
    assert "$323,450.02" in html


def test_render_html_escapes_label_html() -> None:
    """A label containing HTML-significant characters must not break out of its element."""
    html = bsr.render_html("T", "D", [{"label": "A & B <script>", "value": 1.0}], "")
    assert "<script>" not in html
    assert "A &amp; B &lt;script&gt;" in html


def test_load_rows_rejects_non_list(tmp_path: Path) -> None:
    """A data file that isn't a JSON array must fail loudly, not silently produce zero rows."""
    path = tmp_path / "rows.json"
    path.write_text(json.dumps({"label": "x", "value": 1}), encoding="utf-8")
    with pytest.raises(SystemExit):
        bsr._load_rows(path)  # pylint: disable=protected-access


def test_load_rows_rejects_missing_keys(tmp_path: Path) -> None:
    """An object missing 'label' or 'value' must fail loudly rather than crash deep in rendering."""
    path = _rows_file(tmp_path, [{"label": "only label"}])
    with pytest.raises(SystemExit):
        bsr._load_rows(path)  # pylint: disable=protected-access


def test_build_writes_synthetic_manifest(tmp_path: Path) -> None:
    """A fresh slug dir gets a manifest tagged synthetic, with empty capabilities and real rows."""
    slug_dir = tmp_path / "variant-x"
    slug_dir.mkdir()
    data_file = _rows_file(tmp_path, REAL_ROWS)
    args = _args(slug_dir, data_file)

    assert bsr.build(args) == 0

    manifest = json.loads((slug_dir / "reference" / "manifest.json").read_text(encoding="utf-8"))
    state = manifest["dashboards"][0]["states"][0]
    assert state["provider"] == bsr.PROVIDER_SYNTHETIC
    assert state["capabilities"] == []
    assert state["synthetic"] is True
    assert "validation_grade" not in state["capabilities"]
    oracle_labels = {r["label"] for r in state["numeric_oracle"]["rows"]}
    assert oracle_labels == {r["label"] for r in REAL_ROWS}


def test_build_refuses_to_overwrite_a_real_manifest_without_force(tmp_path: Path) -> None:
    """A manifest with real (non-empty) dashboard states must not be silently replaced."""
    slug_dir = tmp_path / "variant-y"
    reference_dir = slug_dir / "reference"
    reference_dir.mkdir(parents=True)
    real_manifest = {
        "captured_at": "2026-01-01T00:00:00Z",
        "source_workbook_sha256": "abc",
        "dashboards": [{"name": "Overview", "states": [{"provider": "public_playwright"}]}],
    }
    (reference_dir / "manifest.json").write_text(json.dumps(real_manifest), encoding="utf-8")
    data_file = _rows_file(tmp_path, REAL_ROWS)

    assert bsr.build(_args(slug_dir, data_file)) == 1
    # unchanged - still the real provider, not clobbered by the synthetic one
    unchanged = json.loads((reference_dir / "manifest.json").read_text(encoding="utf-8"))
    assert unchanged["dashboards"][0]["states"][0]["provider"] == "public_playwright"


def test_build_allows_upgrading_a_structural_only_manifest_without_force(tmp_path: Path) -> None:
    """An EMPTY dashboards list (the structural-only marker) has nothing real to lose - no --force."""
    slug_dir = tmp_path / "variant-z"
    reference_dir = slug_dir / "reference"
    reference_dir.mkdir(parents=True)
    empty_manifest = {"captured_at": "2026-01-01T00:00:00Z", "source_workbook_sha256": None, "dashboards": []}
    (reference_dir / "manifest.json").write_text(json.dumps(empty_manifest), encoding="utf-8")
    data_file = _rows_file(tmp_path, REAL_ROWS)

    assert bsr.build(_args(slug_dir, data_file)) == 0
    updated = json.loads((reference_dir / "manifest.json").read_text(encoding="utf-8"))
    assert updated["dashboards"][0]["states"][0]["provider"] == bsr.PROVIDER_SYNTHETIC


def test_build_force_overwrites_a_real_manifest(tmp_path: Path) -> None:
    """--force is the explicit, named escape hatch to replace a real capture."""
    slug_dir = tmp_path / "variant-w"
    reference_dir = slug_dir / "reference"
    reference_dir.mkdir(parents=True)
    real_manifest = {
        "captured_at": "2026-01-01T00:00:00Z",
        "source_workbook_sha256": "abc",
        "dashboards": [{"name": "Overview", "states": [{"provider": "public_playwright"}]}],
    }
    (reference_dir / "manifest.json").write_text(json.dumps(real_manifest), encoding="utf-8")
    data_file = _rows_file(tmp_path, REAL_ROWS)

    assert bsr.build(_args(slug_dir, data_file, force=True)) == 0
    updated = json.loads((reference_dir / "manifest.json").read_text(encoding="utf-8"))
    assert updated["dashboards"][0]["states"][0]["provider"] == bsr.PROVIDER_SYNTHETIC


def _args(slug_dir: Path, data_file: Path, force: bool = False) -> argparse.Namespace:
    """argparse.Namespace is simpler and more transparent here than reaching into main()'s parser."""
    return argparse.Namespace(
        slug_dir=str(slug_dir),
        data_file=str(data_file),
        title="Billing by Customer",
        dashboard_name="Overview",
        oracle_source="test",
        unit="$",
        force=force,
    )
