"""Independent held-byte controls for the reduced, exact keyed numeric relation."""

import json
import sys
from decimal import Inexact, Rounded, localcontext
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))
from numeric_comparison import compare_numeric  # noqa: E402  # pylint: disable=wrong-import-position

CSV = b"Region,Item,Amount\nNorth,A,9007199254740993.1250\nSouth,B,-0.500\n"
WIRE = (
    b'{"schema_version":1,"query_sha256":"0000000000000000000000000000000000000000000000000000000000000000",'
    b'"columns":[{"name":"[region]","kind":"string"},{"name":"[item]","kind":"string"},'
    b'{"name":"[amount]","kind":"decimal"}],"rows":['
    b'[{"kind":"string","value":"North"},{"kind":"string","value":"A"},'
    b'{"kind":"decimal","value":"9007199254740993.1250"}],'
    b'[{"kind":"string","value":"South"},{"kind":"string","value":"B"},{"kind":"decimal","value":"-0.500"}]]}'
)
KEYS = (("Region", "[region]"), ("Item", "[item]"))
VALUES = (("Amount", "[amount]"),)


def _compare(csv: bytes = CSV, wire: bytes = WIRE, **overrides: object) -> str:
    arguments = {
        "csv_bytes": csv,
        "typed_bytes": wire,
        "key_columns": KEYS,
        "value_columns": VALUES,
        "csv_max_payload_bytes": max(1, len(csv)),
        "typed_max_payload_bytes": max(1, len(wire)),
    }
    arguments.update(overrides)
    return compare_numeric(**arguments)


def _payload() -> dict:
    return json.loads(WIRE)


def _wire(payload: dict) -> bytes:
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")


def _row(region: str, item: str, amount: str | None, kind: str = "decimal") -> list[dict]:
    return [
        {"kind": "string", "value": region},
        {"kind": "string", "value": item},
        {"kind": "blank" if amount is None else kind, "value": amount},
    ]


def test_nonempty_literal_operands_are_equal() -> None:
    """Neither side of the positive control is generated by production code."""
    assert _compare() == "EQUAL"


def test_one_value_mutation_beyond_float_precision_is_different() -> None:
    """One changed DAX value must not disappear into a binary float."""
    changed = _payload()
    changed["rows"][0][2]["value"] = "9007199254740992.1250"
    assert _compare() == "EQUAL"
    assert _compare(wire=_wire(changed)) == "DIFFERENT"


def test_decimal_equality_ignores_scale_and_the_global_context() -> None:
    """Exact construction/equality must neither round nor change the ambient context."""
    changed = _payload()
    changed["rows"][0][2]["value"] = "9007199254740993.125"
    changed["rows"][1][2]["value"] = "-0.500000"
    with localcontext() as context:
        context.prec = 1
        context.traps[Inexact] = context.traps[Rounded] = True
        context.clear_flags()
        assert _compare(wire=_wire(changed)) == "EQUAL"
        changed["rows"][0][2]["value"] = "9007199254740993.126"
        assert _compare(wire=_wire(changed)) == "DIFFERENT"
        assert context.prec == 1
        assert not any(context.flags.values())


@pytest.mark.parametrize("kind,text", [("int32", "1"), ("int64", "1"), ("decimal", "1.00000")])
def test_kind_and_scale_are_not_display_fidelity(kind: str, text: str) -> None:
    """The same mathematical number may arrive with any supported numeric kind."""
    payload = _payload()
    payload["columns"][2]["kind"] = kind
    payload["rows"] = [_row("North", "A", text, kind)]
    assert _compare(b"Region,Item,Amount\nNorth,A,1.0\n", _wire(payload)) == "EQUAL"


@pytest.mark.parametrize(
    "kind,text",
    [
        ("int32", "-2147483648"),
        ("int32", "2147483647"),
        ("int64", "-9223372036854775808"),
        ("int64", "9223372036854775807"),
        ("decimal", "-0.000"),
    ],
)
def test_numeric_domain_endpoints_are_exact(kind: str, text: str) -> None:
    """Int64 endpoints and signed zero are not converted through float."""
    payload = _payload()
    payload["columns"][2]["kind"] = kind
    payload["rows"] = [_row("North", "A", text, kind)]
    csv = f"Region,Item,Amount\nNorth,A,{text}\n".encode()
    assert _compare(csv, _wire(payload)) == "EQUAL"


def test_composite_keys_are_tuples_not_delimiter_concatenations() -> None:
    """These two keys collide if their components are joined with a pipe."""
    csv = b"Region,Item,Amount\na|b,c,1\na,b|c,2\n"
    payload = _payload()
    payload["rows"] = [_row("a|b", "c", "1"), _row("a", "b|c", "2")]
    assert _compare(csv, _wire(payload)) == "EQUAL"
    payload["rows"][0][2]["value"], payload["rows"][1][2]["value"] = "2", "1"
    assert _compare(csv, _wire(payload)) == "DIFFERENT"


def test_rows_and_explicitly_mapped_columns_can_be_reordered() -> None:
    """Order is immaterial; complete keyed identity and mapped values are not."""
    payload = _payload()
    order = (2, 0, 1)
    payload["columns"] = [payload["columns"][index] for index in order]
    payload["rows"] = [[row[index] for index in order] for row in reversed(payload["rows"])]
    assert _compare(wire=_wire(payload)) == "EQUAL"


@pytest.mark.parametrize("variant", ["missing", "extra", "changed"])
def test_different_unique_key_sets_are_different(variant: str) -> None:
    """A missing, additional, or substituted DAX key is a valid difference."""
    payload = _payload()
    if variant == "missing":
        payload["rows"].pop()
    elif variant == "extra":
        payload["rows"].append(_row("West", "C", "1"))
    else:
        payload["rows"][0][0]["value"] = "West"
    assert _compare(wire=_wire(payload)) == "DIFFERENT"


@pytest.mark.parametrize("side", ["csv", "typed"])
@pytest.mark.parametrize("changed_value", [False, True])
def test_duplicate_keys_refuse_instead_of_deduplicating(side: str, changed_value: bool) -> None:
    """Both identical and value-conflicting duplicate keys are outside the domain."""
    if side == "csv":
        extra = b"North,A,7\n" if changed_value else b"North,A,9007199254740993.1250\n"
        result = _compare(CSV + extra)
    else:
        payload = _payload()
        amount = "7" if changed_value else "9007199254740993.1250"
        payload["rows"].append(_row("North", "A", amount))
        result = _compare(wire=_wire(payload))
    assert result == "KEY_DUPLICATE"


@pytest.mark.parametrize("key", ["north", " North", "North ", "NORTH"])
def test_keys_are_not_trimmed_or_casefolded(key: str) -> None:
    """Changed text remains a different key, including leading/trailing whitespace."""
    payload = _payload()
    payload["rows"][0][0]["value"] = key
    assert _compare(wire=_wire(payload)) == "DIFFERENT"


def test_utf8_keys_are_not_unicode_normalized() -> None:
    """Canonically equivalent Unicode is not the same exact text."""
    csv = b"Region,Item,Amount\n\xc3\xa9,A,1\n"
    payload = _payload()
    payload["rows"] = [_row("\u00e9", "A", "1")]
    assert _compare(csv, _wire(payload)) == "EQUAL"
    payload["rows"][0][0]["value"] = "e\u0301"
    assert _compare(csv, _wire(payload)) == "DIFFERENT"


def test_quoted_csv_decoding_preserves_embedded_text_exactly() -> None:
    """Commas, doubled quotes, and embedded CRLF are text, not normalization opportunities."""
    csv = b'Region,Item,Amount\r\n"North,\r\n""N"""," ","1.0"\r\n'
    payload = _payload()
    payload["rows"] = [_row('North,\r\n"N"', " ", "1")]
    assert _compare(csv, _wire(payload)) == "EQUAL"


def test_complete_zero_row_operands_are_empty() -> None:
    """Header/envelope validation still occurs when both sides have no data."""
    payload = _payload()
    payload["rows"] = []
    assert _compare(b"Region,Item,Amount\n", _wire(payload)) == "EMPTY"


@pytest.mark.parametrize("side", ["csv", "typed"])
def test_exactly_one_zero_row_operand_is_different(side: str) -> None:
    """A valid empty side differs from a valid nonempty side."""
    payload = _payload()
    if side == "typed":
        payload["rows"] = []
    csv = b"Region,Item,Amount\n" if side == "csv" else CSV
    assert _compare(csv, _wire(payload)) == "DIFFERENT"


def test_empty_does_not_bypass_validation_of_the_other_side() -> None:
    """Neither the empty nor the different outcome can excuse malformed values."""
    payload = _payload()
    payload["rows"][0][2]["value"] = "NaN"
    assert _compare(b"Region,Item,Amount\n", _wire(payload)) == "VALUE_UNSUPPORTED"
    payload["rows"] = []
    assert _compare(b"Region,Item,Amount\nNorth,A,NaN\n", _wire(payload)) == "VALUE_UNSUPPORTED"


@pytest.mark.parametrize(
    "csv",
    [
        b"",
        b"\n",
        b'""\n',
        b"\xff",
        b'Region,Item,Amount\n"North,A,1',
        b'Region,Item,Amount\n"N"orth,A,1\n',
        b'Region,Item,Amount\nNor"th,A,1\n',
        b"Region,Item,Amount\nNorth,A\n",
        b"Region,Item,Amount\nNorth,A,1,extra\n",
        b"Region,Item,Amount\n\n",
    ],
)
def test_empty_headerless_or_malformed_csv_is_refused(csv: bytes) -> None:
    """Malformed/absent CSV cannot be an empty successful comparison."""
    assert _compare(csv) == "CSV_INVALID"


@pytest.mark.parametrize(
    "number",
    [".5", "1.", "01", "+1", "1e2", "1E+2", "\u0661", "\uff11", " 1", "1 ", "\t1", "1,000", "$1", "1%", "1.234,56", ""],
)
def test_csv_numeric_grammar_is_ascii_and_locale_free(number: str) -> None:
    """Quoting a numeric cell does not relax its decoded grammar."""
    csv = f'Region,Item,Amount\nNorth,A,"{number}"\n'.encode("utf-8")
    assert _compare(csv) == "VALUE_UNSUPPORTED"


def test_unquoted_empty_numeric_cell_is_not_zero_or_blank() -> None:
    """An empty CSV value has no admitted NULL convention."""
    assert _compare(b"Region,Item,Amount\nNorth,A,\n") == "VALUE_UNSUPPORTED"


@pytest.mark.parametrize("side", ["csv", "typed"])
def test_empty_text_key_refuses(side: str) -> None:
    """A key must have a nonempty value on both sides."""
    payload = _payload()
    payload["rows"][0][0]["value"] = ""
    if side == "csv":
        assert _compare(b"Region,Item,Amount\n,A,1\n") == "KEY_INVALID"
    else:
        assert _compare(wire=_wire(payload)) == "KEY_INVALID"


def test_blank_key_refuses_but_blank_numeric_differs() -> None:
    """BLANK has a meaning in numeric comparison, but cannot be a text key."""
    payload = _payload()
    payload["rows"][0][0] = {"kind": "blank", "value": None}
    assert _compare(wire=_wire(payload)) == "KEY_INVALID"
    payload = _payload()
    payload["rows"][0][2] = {"kind": "blank", "value": None}
    assert _compare(wire=_wire(payload)) == "DIFFERENT"


@pytest.mark.parametrize("kind", ["boolean", "double", "date", "datetime", "object", "Decimal"])
@pytest.mark.parametrize("where", ["column", "cell"])
def test_unsupported_typed_kinds_are_fixed_refusals(kind: str, where: str) -> None:
    """There is no fallback to str(), float(), a date parser, or another comparison mode."""
    payload = _payload()
    if where == "column":
        payload["columns"][2]["kind"] = kind
    else:
        payload["rows"][0][2]["kind"] = kind
    assert _compare(wire=_wire(payload)) == "VALUE_UNSUPPORTED"


@pytest.mark.parametrize(
    "kind,value",
    [
        ("int32", "2147483648"),
        ("int32", "-2147483649"),
        ("int64", "9223372036854775808"),
        ("int64", "-9223372036854775809"),
        ("int64", "1.0"),
        ("int64", "9" * 5000),
        ("decimal", "NaN"),
        ("decimal", "Infinity"),
        ("decimal", "1e0"),
        ("decimal", "01"),
        ("decimal", ""),
    ],
)
def test_typed_numeric_values_must_match_the_declared_domain(kind: str, value: str) -> None:
    """Malformed, out-of-range, and nonfinite numbers refuse rather than coerce."""
    payload = _payload()
    payload["columns"][2]["kind"] = kind
    payload["rows"] = [_row("North", "A", value, kind)]
    assert _compare(wire=_wire(payload)) == "VALUE_UNSUPPORTED"


@pytest.mark.parametrize("position,kind,expected", [(0, "int32", "KEY_INVALID"), (2, "string", "VALUE_UNSUPPORTED")])
def test_key_and_value_roles_are_not_inferred(position: int, kind: str, expected: str) -> None:
    """Text-looking numbers do not turn a value column into a key or vice versa."""
    payload = _payload()
    payload["columns"][position]["kind"] = kind
    for row in payload["rows"]:
        row[position] = {"kind": kind, "value": "1"}
    assert _compare(wire=_wire(payload)) == expected


@pytest.mark.parametrize(
    "wire",
    [
        b"",
        b"null",
        b"[]",
        b"{}",
        b'{"error":"EXECUTION_FAILED"}',
        b"\xff",
        WIRE + b"{}",
        WIRE.replace(b'"schema_version":1', b'"schema_version":true'),
        WIRE.replace(b'"schema_version":1', b'"schema_version":1.0'),
        WIRE.replace(b'"schema_version":1', b'"schema_version":2'),
        WIRE.replace(b'"schema_version":1', b'"schema_version":1,"schema_version":1'),
        WIRE.replace(b'"value":"North"', b'"value":"North","value":"North"'),
        WIRE.replace(b'"value":"North"', b'"value":"\\ud800"'),
        WIRE.replace(b'"value":"9007199254740993.1250"', b'"value":NaN'),
        WIRE.replace(b'"value":"9007199254740993.1250"', b'"value":1'),
    ],
)
def test_typed_structure_is_closed_and_strict(wire: bytes) -> None:
    """Do not accept nonstandard JSON, duplicate members, lossy numeric cells, or other envelopes."""
    assert _compare(wire=wire) == "TYPED_INVALID"


@pytest.mark.parametrize(
    "variant", ["extra_field", "bad_hash", "missing_cell", "extra_cell", "wrong_kind", "bad_blank"]
)
def test_structural_mutations_refuse_exactly(variant: str) -> None:
    """Each mutation changes only one structural arm of a known-valid envelope."""
    payload = _payload()
    if variant == "extra_field":
        payload["unexpected"] = True
    elif variant == "bad_hash":
        payload["query_sha256"] = "A" * 64
    elif variant == "missing_cell":
        payload["rows"][0].pop()
    elif variant == "extra_cell":
        payload["rows"][0].append({"kind": "decimal", "value": "1"})
    elif variant == "wrong_kind":
        payload["rows"][0][2]["kind"] = "int64"
    else:
        payload["rows"][0][2] = {"kind": "blank", "value": "0"}
    assert _compare(wire=_wire(payload)) == "TYPED_INVALID"


def test_query_hash_is_validated_but_not_bound_to_a_request() -> None:
    """Receipt/request authority is deliberately absent from this comparator."""
    payload = _payload()
    payload["query_sha256"] = "f" * 64
    assert _compare(wire=_wire(payload)) == "EQUAL"


@pytest.mark.parametrize(
    "overrides",
    [
        {"key_columns": []},
        {"value_columns": []},
        {"key_columns": None},
        {"key_columns": {"Region": "[region]", "Item": "[item]"}},
        {"key_columns": [("Region", "[region]")]},
        {"key_columns": [("Region", "[region]"), ("Region", "[item]")]},
        {"key_columns": [("Region", "[region]"), ("Item", "[region]")]},
        {"key_columns": [("Region", "[region]"), ("Item", "[missing]")]},
        {"value_columns": [("Amount", "[amount]"), ("Amount", "[amount]")]},
        {"value_columns": [("Amount",)]},
        {"value_columns": [(None, "[amount]")]},
        {"value_columns": [("\ud800", "[amount]")]},
    ],
)
def test_mappings_must_be_explicit_complete_and_bijective(overrides: dict) -> None:
    """Missing, duplicate, invalid, or inferred mappings are never silently repaired."""
    assert _compare(**overrides) == "COLUMNS_INVALID"


@pytest.mark.parametrize("side", ["csv", "typed"])
def test_duplicate_column_names_refuse(side: str) -> None:
    """A mapping cannot select between two identically named columns."""
    payload = _payload()
    payload["columns"][1]["name"] = "[region]"
    if side == "csv":
        assert _compare(CSV.replace(b"Region,Item,Amount", b"Region,Region,Amount")) == "COLUMNS_INVALID"
    else:
        assert _compare(wire=_wire(payload)) == "COLUMNS_INVALID"


def test_empty_or_extra_columns_cannot_be_ignored() -> None:
    """Even a zero-row envelope needs a complete, nonempty mapped header."""
    assert _compare(b"Region,Item,Amount,Ignored\n") == "COLUMNS_INVALID"
    assert _compare(CSV.replace(b"Region,Item,Amount", b"Region,,Amount")) == "COLUMNS_INVALID"
    payload = _payload()
    payload["columns"], payload["rows"] = [], []
    assert _compare(b"Region,Item,Amount\n", _wire(payload)) == "COLUMNS_INVALID"


@pytest.mark.parametrize("parameter", ["csv_max_payload_bytes", "typed_max_payload_bytes"])
@pytest.mark.parametrize("limit", [None, 0, -1, True, False, 1.0, "1000"])
def test_each_operand_requires_a_positive_integer_byte_budget(parameter: str, limit: object) -> None:
    """No default, boolean budget, or coerced numeric string is admitted."""
    assert _compare(**{parameter: limit}) == "INPUT_INVALID"


@pytest.mark.parametrize("parameter", ["csv_bytes", "typed_bytes"])
@pytest.mark.parametrize("operand", [None, "", bytearray(b"x"), 1])
def test_operands_are_held_bytes_not_paths_or_mutable_buffers(parameter: str, operand: object) -> None:
    """The comparator does not discover, read, execute, or coerce its operands."""
    assert _compare(**{parameter: operand}) == "INPUT_INVALID"


def test_exact_original_byte_limits_and_one_byte_over() -> None:
    """Charge the original CSV and whole wire envelope, not a smaller JSON serialization."""
    padded = b" \t" + WIRE + b"  "
    assert _compare(wire=padded, csv_max_payload_bytes=len(CSV), typed_max_payload_bytes=len(padded)) == "EQUAL"
    assert _compare(wire=padded, csv_max_payload_bytes=len(CSV) - 1) == "PAYLOAD_LIMIT"
    assert _compare(wire=padded, typed_max_payload_bytes=len(padded) - 1) == "PAYLOAD_LIMIT"
    assert _compare(wire=padded, typed_max_payload_bytes=len(WIRE)) == "PAYLOAD_LIMIT"


@pytest.mark.parametrize("framing", [b"\n", b"\r\n"])
def test_ndjson_newline_is_framing_not_envelope_budget(framing: bytes) -> None:
    """Only the one transport terminator is excluded, not JSON whitespace."""
    assert _compare(wire=WIRE + framing, typed_max_payload_bytes=len(WIRE)) == "EQUAL"
    assert _compare(wire=WIRE + b" " + framing, typed_max_payload_bytes=len(WIRE)) == "PAYLOAD_LIMIT"


def test_utf8_wire_bytes_not_character_count_determine_the_budget() -> None:
    """Multibyte text must count its actual received UTF-8 length."""
    csv = b"Region,Item,Amount\n\xc3\xa9,A,1\n"
    payload = _payload()
    payload["rows"] = [_row("\u00e9", "A", "1")]
    wire = _wire(payload)
    assert _compare(csv, wire) == "EQUAL"
    assert _compare(csv, wire, typed_max_payload_bytes=len(wire.decode())) == "PAYLOAD_LIMIT"


def test_no_hidden_csv_field_or_digit_ceiling() -> None:
    """Large text keys and exact zeros beyond csv.reader's usual field limit remain valid."""
    key = "k" * 140_000
    zero = "0." + "0" * 140_000
    csv = f"Region,Item,Amount\n{key},A,{zero}\n".encode()
    payload = _payload()
    payload["rows"] = [_row(key, "A", "0.0000")]
    assert _compare(csv, _wire(payload)) == "EQUAL"


def test_refusal_diagnostics_never_contain_operand_text(capsys: pytest.CaptureFixture[str]) -> None:
    """Refusals are codes, not data-bearing explanations or logs."""
    sentinel = b"SENSITIVE_A2_KEY_VALUE"
    csv = b"Region,Item,Amount\n" + sentinel + b",A," + sentinel + b"\n"
    assert _compare(csv) == "VALUE_UNSUPPORTED"
    captured = capsys.readouterr()
    assert captured.out == captured.err == ""


def test_one_explicit_key_and_every_mapped_numeric_value_are_compared() -> None:
    """A second numeric value is not an ignored column; a single text-key component is sufficient."""
    csv = b"Key,Small,Large,Amount\nA,7,9223372036854775807,9007199254740993.1250\n"
    payload = {
        "schema_version": 1,
        "query_sha256": "0" * 64,
        "columns": [
            {"name": "k", "kind": "string"},
            {"name": "s", "kind": "int32"},
            {"name": "l", "kind": "int64"},
            {"name": "a", "kind": "decimal"},
        ],
        "rows": [
            [
                {"kind": "string", "value": "A"},
                {"kind": "int32", "value": "7"},
                {"kind": "int64", "value": "9223372036854775807"},
                {"kind": "decimal", "value": "9007199254740993.1250"},
            ]
        ],
    }
    mapping = {"key_columns": (("Key", "k"),), "value_columns": (("Small", "s"), ("Large", "l"), ("Amount", "a"))}
    assert _compare(csv, _wire(payload), **mapping) == "EQUAL"
    for index, changed in ((1, "8"), (2, "9223372036854775806"), (3, "9007199254740993.1251")):
        original = payload["rows"][0][index]["value"]
        payload["rows"][0][index]["value"] = changed
        assert _compare(csv, _wire(payload), **mapping) == "DIFFERENT"
        payload["rows"][0][index]["value"] = original


def test_json_escaping_is_charged_at_its_received_wire_size() -> None:
    """Equivalent decoded values do not permit shrinking the admitted byte count."""
    escaped = WIRE.replace(b'"North"', b'"\\u004eorth"')
    assert _compare(wire=escaped) == "EQUAL"
    assert _compare(wire=escaped, typed_max_payload_bytes=len(escaped) - 1) == "PAYLOAD_LIMIT"


def test_csv_final_record_does_not_require_a_newline() -> None:
    """Valid EOF after a field or quoted field is not a malformed CSV record."""
    assert _compare(CSV.rstrip(b"\n")) == "EQUAL"
    payload = _payload()
    payload["rows"] = []
    assert _compare(b"Region,Item,Amount", _wire(payload)) == "EMPTY"


@pytest.mark.parametrize(
    "text,expected",
    [
        ("79228162514264337593543950335", "EQUAL"),
        ("-79228162514264337593543950335", "EQUAL"),
        ("79228162514264337593543950336", "VALUE_UNSUPPORTED"),
        ("-79228162514264337593543950336", "VALUE_UNSUPPORTED"),
        ("7.9228162514264337593543950335", "EQUAL"),
        ("-7.9228162514264337593543950335", "EQUAL"),
        ("7.9228162514264337593543950336", "VALUE_UNSUPPORTED"),
        ("-7.9228162514264337593543950336", "VALUE_UNSUPPORTED"),
        ("0.0000000000000000000000000001", "EQUAL"),
        ("-0.0000000000000000000000000001", "EQUAL"),
        ("0.00000000000000000000000000001", "VALUE_UNSUPPORTED"),
        ("-0.00000000000000000000000000001", "VALUE_UNSUPPORTED"),
        ("0.00000000000000000000000000000", "VALUE_UNSUPPORTED"),
        ("1.0000000000000000000000000000", "EQUAL"),
        ("1.00000000000000000000000000000", "VALUE_UNSUPPORTED"),
        ("79228162514264337593543950335.0", "VALUE_UNSUPPORTED"),
        ("-0.0000000000000000000000000000", "EQUAL"),
    ],
)
def test_typed_decimal_requires_its_exact_clr_coefficient_and_scale(text: str, expected: str) -> None:
    """The declared scale must fit, not merely a value obtainable by trimming trailing zeros."""
    payload = _payload()
    payload["rows"] = [_row("North", "A", text)]
    csv = f"Region,Item,Amount\nNorth,A,{text}\n".encode()
    with localcontext() as context:
        context.prec = 1
        context.traps[Inexact] = context.traps[Rounded] = True
        context.clear_flags()
        assert _compare(csv, _wire(payload)) == expected
        assert not any(context.flags.values())


@pytest.mark.parametrize(
    "csv_number,typed_number,expected",
    [
        ("79228162514264337593543950336", "79228162514264337593543950335", "DIFFERENT"),
        ("-79228162514264337593543950336", "-79228162514264337593543950335", "DIFFERENT"),
        ("0.00000000000000000000000000001", "0.0000", "DIFFERENT"),
        ("1.00000000000000000000000000000", "1", "EQUAL"),
        ("79228162514264337593543950335.0", "79228162514264337593543950335", "EQUAL"),
    ],
)
def test_csv_numbers_do_not_acquire_the_clr_decimal_domain(csv_number: str, typed_number: str, expected: str) -> None:
    """CLR representability constrains only typed cells, never the admitted CSV numeric grammar."""
    payload = _payload()
    payload["rows"] = [_row("North", "A", typed_number)]
    csv = f"Region,Item,Amount\nNorth,A,{csv_number}\n".encode()
    with localcontext() as context:
        context.prec = 1
        assert _compare(csv, _wire(payload)) == expected
