"""The seed workbook must be well-formed XML, and must still be a workbook the engine can type.

Every assertion here pins something that was, or could silently become, broken while every existing
gate stayed green - the file is generated by string formatting, so nothing between `build_twbx` and
Tableau's own parser ever looked at the result.

Three classes of defect:

* **Escaping.** Every attribute in `TWB_TEMPLATE` is single-quoted, but `saxutils.escape` covers only
  `&`, `<` and `>`. Seed names are `"Seed - " + <live project name>`, so a project called `L'Equipe`
  closed the attribute early and the whole file stopped being XML.
* **Truncation.** Composing the sheet name and slicing the ESCAPED result cut entities in half, and
  for a long enough name made the worksheet and the dashboard the same string - which Tableau
  rejects, because a sheet name must be unique across worksheets AND dashboards.
* **Content.** `<metadata-records>` and the packaged CSV are what let the migration engine type a
  model; without them the estate comes back `DOD_FAILED, bound=0/N`. Both are plain strings in this
  module, so a careless edit removes them with no other symptom.
"""

from __future__ import annotations

import csv
import io
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "scripts"))

import make_seed_workbook as seed  # noqa: E402  # pylint: disable=wrong-import-position


def _build(name: str, tmp_path: Path) -> tuple[str, str]:
    """Build a seed and return `(twb_xml_text, csv_text)`."""
    out = seed.build_twbx(name, tmp_path / "seed.twbx")
    with zipfile.ZipFile(out) as archive:
        twb = next(n for n in archive.namelist() if n.endswith(".twb"))
        return archive.read(twb).decode("utf8"), archive.read("Data/seed/seed_data.csv").decode("utf8")


def _root(name: str, tmp_path: Path) -> ElementTree.Element:
    return ElementTree.fromstring(_build(name, tmp_path)[0])


# --------------------------------------------------------------------------- escaping


@pytest.mark.parametrize(
    "name",
    [
        "Seed - L'Equipe",  # the apostrophe that closed a single-quoted attribute
        'Seed - He said "hi"',
        "Seed - R&D",
        "Seed - <script>",
        "Seed - a'b&c<d>e\"f",
        "Seed - Ventes francaises",
    ],
)
def test_hostile_names_stay_well_formed_xml(name: str, tmp_path: Path) -> None:
    """An unescaped quote does not corrupt the file subtly - it stops it being XML at all."""
    root = _root(name, tmp_path)
    assert root.find("./datasources/datasource").attrib["caption"] == name


def test_the_apostrophe_survives_the_round_trip_unmangled(tmp_path: Path) -> None:
    """Well-formed is not enough: the name must come back as the name, not as `&apos;` literally."""
    root = _root("Seed - L'Equipe", tmp_path)
    assert root.find("./worksheets/worksheet").attrib["name"].startswith("Seed - L'Equipe")


# --------------------------------------------------------------------------- truncation


@pytest.mark.parametrize("length", list(range(40, 70)))
def test_truncation_never_splits_an_xml_entity(length: int, tmp_path: Path) -> None:
    """A `&` near the cut point is the case: escaped it becomes 5 characters, so slicing the escaped
    string can leave a bare `&a`. Measured on the pre-fix code: n=49..52 failed, n=53 passed."""
    name = "x" * (length - 1) + "&"
    _root(name, tmp_path)  # raises ParseError if an entity was cut


@pytest.mark.parametrize("length", [1, 20, 53, 54, 60, 80, 200])
def test_worksheet_and_dashboard_names_never_collide(length: int, tmp_path: Path) -> None:
    """Tableau requires a sheet name unique ACROSS worksheets and dashboards. Composing then slicing
    at 60 made both `name[:60]` for any name of 54 characters or more."""
    root = _root("n" * length, tmp_path)
    sheet = root.find("./worksheets/worksheet").attrib["name"]
    dashboard = root.find("./dashboards/dashboard").attrib["name"]
    assert sheet != dashboard
    assert len(sheet) <= seed.MAX_SHEET_NAME and len(dashboard) <= seed.MAX_SHEET_NAME


def test_the_dashboard_zone_still_points_at_the_worksheet(tmp_path: Path) -> None:
    """Making the two names differ is worthless if the dashboard now references a sheet that does not
    exist - the workbook would publish and open empty."""
    root = _root("z" * 80, tmp_path)
    sheet = root.find("./worksheets/worksheet").attrib["name"]
    assert root.find(".//dashboards/dashboard/zones/zone/zone").attrib["name"] == sheet
    assert root.find(".//windows/window[@class='dashboard']/viewpoints/viewpoint").attrib["name"] == sheet


def test_every_worksheet_has_a_window(tmp_path: Path) -> None:
    """Measured against Tableau Cloud: publishing without one fails `not associated with any window`."""
    root = _root("Seed - Anything", tmp_path)
    sheets = {w.attrib["name"] for w in root.findall("./worksheets/worksheet")}
    windows = {w.attrib["name"] for w in root.findall("./windows/window[@class='worksheet']")}
    assert sheets and sheets <= windows


# --------------------------------------------------------------------------- content


def test_every_column_carries_a_metadata_record(tmp_path: Path) -> None:
    """Without `<metadata-records>` the engine cannot type a model and the whole estate comes back
    `DOD_FAILED, bound=0/N` - a failure that appears three tools downstream, not here."""
    root = _root("Seed - Typed", tmp_path)
    records = root.findall(".//metadata-records/metadata-record")
    assert len(records) == 2
    typed = {r.findtext("local-name"): r.findtext("local-type") for r in records}
    assert typed == {"[region]": "string", "[amount]": "integer"}
    assert {r.findtext("remote-name") for r in records} == {"region", "amount"}


def test_the_packaged_csv_is_real_data_matching_the_declared_columns(tmp_path: Path) -> None:
    """The CSV is a plain string constant, so a broken value produces a workbook that still publishes
    and still parses as XML - and holds no data at all."""
    twb, data = _build("Seed - Data", tmp_path)
    rows = list(csv.DictReader(io.StringIO(data)))
    assert [f.strip() for f in csv.reader(io.StringIO(data)).__next__()] == ["region", "amount"]
    assert len(rows) == 3
    assert all(row["region"] and row["amount"].strip().isdigit() for row in rows)

    declared = {c.attrib["name"] for c in ElementTree.fromstring(twb).findall(".//relation/columns/column")}
    assert declared == set(rows[0])


def test_the_archive_holds_exactly_the_two_entries_the_template_names(tmp_path: Path) -> None:
    """The relation's `directory`/`filename` pair must agree with the packaged path or the workbook
    opens broken, and a `/` in the name must not create a DIRECTORY inside the zip."""
    out = seed.build_twbx("Seed - R/D", tmp_path / "s.twbx")
    with zipfile.ZipFile(out) as archive:
        assert sorted(archive.namelist()) == ["Data/seed/seed_data.csv", "Seed - R_D.twb"]


def test_the_seed_marker_constant_matches_the_template() -> None:
    """`provision_tableau_estate.py` refuses to Overwrite a workbook that does not carry this marker.
    If the constant and the template drift, that check silently protects nothing - or refuses to
    refresh a seed it really did publish."""
    assert seed.TWB_TEMPLATE.count(seed.SEED_DATASOURCE_NAME) >= 3


def test_a_seed_stays_tiny(tmp_path: Path) -> None:
    """The fixture's value is its LOCATION; size is what makes seeding a dozen projects free."""
    assert seed.build_twbx("Seed - Small", tmp_path / "s.twbx").stat().st_size < 5_000
