"""Direct #562 prerequisite controls, not an implementation of the final START_READY consumer.

Hand-built S1/S2 fixtures and literal projection/key oracles separate bytes, binding and applicability.
No audit, credential change, probe, source search, provider permission or final readiness fold here.
"""

from __future__ import annotations

import copy
import hashlib
import inspect
import json
import os
import shutil
import stat
from dataclasses import fields, replace
from pathlib import Path

import pytest

from test_package_filesystem import build_package, classify, link_directory, verify, write_manifest
from test_package_role_identity import (
    DS_LUID,
    PUBLISHED_KEY,
    WB_LUID,
    datasource_package,
    pri,
    seal,
    workbook_package,
)

import credential_gate as gate
import package_filesystem as pfs

# pylint: disable=protected-access,missing-function-docstring

SPEC = "migration-spec.json"
PROJECTION = "data-access.json"
LIVE = {"class": "sqlserver", "server": "source.example", "database": "db", "powerbi_target": "live_source"}
OTHER = {**LIVE, "server": "other.example"}
FLAT = {"class": "excel-direct", "powerbi_target": "flat_file"}
REVIEW = {"class": "unknown", "server": "review.example", "powerbi_target": "unknown"}
# Independent SHA-256 of the canonical endpoint JSON, not generated by package_spec_facts().
LIVE_KEY = "source-key:ab1baa4b3f77bb70"
OTHER_KEY = "source-key:e625ce798a6d19bb"
LOCAL_PROJECTION = {
    "schema": "phase1-data-access/v1",
    "state": "local_import_ready",
    "source_keys": [],
    "provider_unit": None,
    "provider_state": None,
    "validation": "validated",
    "effective_scope": "model_only",
    "max_phase2_claim": "data_validated",
    "codes": ["all-flat-file", "package-self-contained"],
}
LIVE_PROJECTION = {
    **LOCAL_PROJECTION,
    "state": "live_data_ok",
    "source_keys": [LIVE_KEY],
    "codes": ["probe-cleared", "probe-data-ok"],
}
PUBLISHED = {
    "id": "ds",
    "connection": {"class": "sqlproxy", "mode": "live"},
    "published_datasource": {"luid": DS_LUID, "key": PUBLISHED_KEY},
}


def source_rows(*connections: dict) -> list[dict]:
    """A minimal spec row, retaining real canonical connection classification."""
    return [{"connection": dict(connection), "tables": [], "fields": []} for connection in connections]


def with_data_access(package: Path, rows: list | None = None, projection: dict | bytes | None = None) -> Path:
    """Declare exact role bytes without invoking the producer or authority under test."""
    spec = json.loads((package / SPEC).read_bytes())
    if rows is not None:
        spec["data_sources"] = copy.deepcopy(rows)
    (package / SPEC).write_bytes(json.dumps(spec, ensure_ascii=False).encode("utf-8"))
    raw = projection if isinstance(projection, bytes) else json.dumps(projection or LOCAL_PROJECTION).encode("utf-8")
    (package / PROJECTION).write_bytes(raw)
    manifest = json.loads((package / "package-manifest.json").read_bytes())
    manifest["artifacts"]["data_access"] = PROJECTION
    return seal(package, **manifest)


def filesystem_package(root: Path) -> Path:
    package = build_package(root, files={SPEC: "", PROJECTION: ""})
    (package / SPEC).write_bytes(b'{"data_sources":[]}\r\n')
    (package / PROJECTION).write_bytes(b'{"held":true}\r\n')
    write_manifest(package)
    return package


def require_held(value: object) -> pfs.HeldVerifiedMember:
    assert isinstance(value, pfs.HeldVerifiedMember), value
    return value


def require_handoff(value: object) -> pri.PackageDataAccessHandoff:
    assert isinstance(value, pri.PackageDataAccessHandoff), value
    return value


def assert_refusal(value: object, code: str) -> None:
    assert isinstance(value, pfs.PackageFilesystemResult), f"expected typed S1 refusal {code}, got {value!r}"
    assert value.first_code == code
    assert not value.is_clean
    assert all(row.path is None for row in (*value.findings, *value.unassessable))


@pytest.mark.parametrize("name", [SPEC, PROJECTION])
def test_s1_exact_member_bytes_and_digest_are_immutable(tmp_path: Path, name: str) -> None:
    package = filesystem_package(tmp_path)
    expected = (package / name).read_bytes()
    verified = verify(package)
    member = require_held(pfs.read_verified_member(package, verified, name))
    assert member.content == expected
    assert member.sha256 == hashlib.sha256(expected).hexdigest()
    assert member.relative_path == name and member.root_identity == str(package)
    assert type(member.content) is bytes  # pylint: disable=unidiomatic-typecheck
    assert type(verified.verified_files) is tuple  # pylint: disable=unidiomatic-typecheck
    with pytest.raises(AttributeError):
        member.content = b"replacement"
    with pytest.raises(AttributeError):
        verified.verified_files[0].sha256 = "0" * 64
    assert "verified_files" not in verified.as_dict() and "manifest" not in verified.as_dict()


def test_s1_holds_no_large_asset_bytes_and_reader_does_not_parse_manifest(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    package = filesystem_package(tmp_path)
    asset = package / "large.bin"
    with asset.open("wb") as handle:
        for _index in range(3):
            handle.write(b"asset" * (1 << 18))
    write_manifest(package)
    classification = classify(package)
    original = Path.read_bytes
    opened = []

    def read_once(path: Path) -> bytes:
        assert path != asset, "large assets must be streamed, not held in the S1 result"
        opened.append(path.name)
        return original(path)

    monkeypatch.setattr(Path, "read_bytes", read_once)
    verified = pfs.verify_package(package, classification)
    assert verified.is_clean
    assert opened == ["package-manifest.json"]
    assert all(
        not isinstance(getattr(member, field.name), bytes)
        for member in verified.verified_files
        for field in fields(member)
    )
    assert len(verified.manifest.content) < 4096

    def forbidden(*_args: object, **_kwargs: object) -> None:
        pytest.fail("a held member reader reparsed or rediscovered the manifest authority")

    monkeypatch.setattr(pfs, "parse_manifest_text", forbidden)
    monkeypatch.setattr(pfs, "declared_files", forbidden)
    member = require_held(pfs.read_verified_member(package, verified, PROJECTION))
    assert member.content == b'{"held":true}\r\n'
    assert opened == ["package-manifest.json", PROJECTION]


def test_held_member_rechecks_exact_s1_digest(tmp_path: Path) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)
    original = require_held(pfs.read_verified_member(package, verified, PROJECTION))
    path = package / PROJECTION
    before = path.stat()
    path.write_bytes(original.content.replace(b"true", b"null"))
    os.utime(path, ns=(before.st_atime_ns, before.st_mtime_ns))
    assert path.stat().st_size == before.st_size
    assert_refusal(pfs.read_verified_member(package, verified, PROJECTION), "package_file_digest_mismatch")


@pytest.mark.parametrize(
    "change,code",
    [
        ("deleted", "package_file_missing"),
        ("added", "package_file_undeclared"),
        ("other-digest", "package_file_digest_mismatch"),
        ("manifest-digest", "package_file_digest_mismatch"),
        ("same-byte-replacement", "package_member_replaced"),
        ("hardlink", "package_member_replaced"),
        ("directory", "package_file_missing"),
        ("case-alias", "package_file_undeclared"),
    ],
)
def test_held_read_refuses_changed_namespace_or_identity(tmp_path: Path, change: str, code: str) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)
    path = package / PROJECTION
    if change == "deleted":
        path.unlink()
    elif change == "added":
        (package / "extra.bin").write_bytes(b"new")
    elif change in ("other-digest", "manifest-digest"):
        target = package / (SPEC if change == "other-digest" else "package-manifest.json")
        target.write_bytes(target.read_bytes() + b"\n")
    elif change == "same-byte-replacement":
        raw = path.read_bytes()
        path.rename(tmp_path / "retired.bin")
        path.write_bytes(raw)
    elif change == "hardlink":
        os.link(path, tmp_path / "alias.bin")
    elif change == "directory":
        path.unlink()
        path.mkdir()
    else:
        path.rename(package / "renaming")
        (package / "renaming").rename(package / PROJECTION.upper())
    assert_refusal(pfs.read_verified_member(package, verified, PROJECTION), code)


def test_resealing_does_not_rebaseline_a_held_namespace(tmp_path: Path) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)
    (package / PROJECTION).write_bytes(b'{"new":true}')
    write_manifest(package)
    assert verify(package).is_clean, "the replacement is independently consistent, but not the held revision"
    assert_refusal(pfs.read_verified_member(package, verified, PROJECTION), "package_file_digest_mismatch")


@pytest.mark.parametrize("junction", [False, True])
def test_same_byte_replaced_root_never_reuses_s1(tmp_path: Path, junction: bool) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)
    retired = package.rename(tmp_path / "retired")
    if junction:
        link_directory(package, retired)
    else:
        shutil.copytree(retired, package)
    try:
        assert_refusal(pfs.read_verified_member(package, verified, PROJECTION), "package_root_replaced")
    finally:
        if junction:
            if os.name == "nt":
                package.rmdir()
            else:
                package.unlink()


def test_s1_root_identity_is_required_even_for_identical_bytes(tmp_path: Path) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)
    assert require_held(pfs.read_verified_member(package, verified, PROJECTION)).root_identity == str(package)
    foreign = replace(verified, root_identity=str(package).swapcase())
    assert_refusal(pfs.read_verified_member(package, foreign, PROJECTION), "package_root_binding_invalid")


@pytest.mark.parametrize("name", ["DATA-ACCESS.JSON", "./data-access.json", "data-access.json.", "../outside", None])
def test_only_exact_canonical_member_spelling_is_read(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, name: str | None
) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)

    def forbidden(*_args: object, **_kwargs: object) -> None:
        pytest.fail("an unverified spelling reached the filesystem")

    monkeypatch.setattr(pfs, "walk_package", forbidden)
    assert_refusal(pfs.read_verified_member(package, verified, name), "package_member_not_verified")


@pytest.mark.parametrize(
    "mode,code", [(stat.S_IFLNK, "package_entry_reparse"), (stat.S_IFCHR, "package_entry_not_regular")]
)
def test_reparse_and_nonregular_members_refuse_before_read(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, mode: int, code: str
) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)
    original = os.DirEntry.stat

    def changed(entry: os.DirEntry, *, follow_symlinks: bool = True) -> os.stat_result:
        info = original(entry, follow_symlinks=follow_symlinks)
        if entry.name != PROJECTION:
            return info
        values = list(info)
        values[0] = (info.st_mode & ~stat.S_IFMT(info.st_mode)) | mode
        extras = {key: getattr(info, key) for key in ("st_file_attributes", "st_reparse_tag") if hasattr(info, key)}
        return os.stat_result(values, extras)

    def forbidden(_path: Path) -> bytes:
        pytest.fail("a reparse/nonregular member was read")

    monkeypatch.setattr(os.DirEntry, "stat", changed)
    monkeypatch.setattr(Path, "read_bytes", forbidden)
    assert_refusal(pfs.read_verified_member(package, verified, PROJECTION), code)


def test_case_colliding_manifest_cannot_publish_a_verified_namespace(tmp_path: Path) -> None:
    package = filesystem_package(tmp_path)
    hashes = {name: hashlib.sha256((package / name).read_bytes()).hexdigest() for name in (SPEC, PROJECTION)}
    write_manifest(package, files={**hashes, PROJECTION.upper(): hashes[PROJECTION]})
    result = verify(package)
    assert result.first_code == "package_declared_keys_collide"
    assert (result.verified_files, result.manifest) == ((), None)


def test_unreadable_member_returns_only_fixed_s1_diagnostics(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    package = filesystem_package(tmp_path)
    verified = verify(package)

    def denied(_path: Path) -> bytes:
        raise PermissionError("PRIVATE endpoint source-name audit path credential")

    monkeypatch.setattr(Path, "read_bytes", denied)
    result = pfs.read_verified_member(package, verified, PROJECTION)
    assert_refusal(result, "package_file_unreadable")
    assert result.status == "unassessable"
    serialized = json.dumps(result.as_dict())
    assert "PRIVATE" not in serialized and str(package) not in serialized and '"path"' not in serialized


def test_s2_handoff_carries_current_live_keys(tmp_path: Path) -> None:
    package = with_data_access(
        datasource_package(tmp_path / "Source", luid=None), source_rows(OTHER, LIVE), LIVE_PROJECTION
    )
    result = pri.verify_phase1_role_identity([package])[0]
    assert result.is_start_ready, result.codes()
    handoff = require_handoff(result.data_access_handoff(package))
    assert handoff.facts.live_source_keys == (LIVE_KEY, OTHER_KEY), "the current live-key handoff was lost"
    assert handoff.facts.direct_applicable and not handoff.facts.all_flat
    assert not handoff.facts.has_review and handoff.facts.refusal_code is None
    assert handoff.migration_spec.content == (package / SPEC).read_bytes()
    assert handoff.data_access.content == (package / PROJECTION).read_bytes()
    assert handoff.migration_spec.root_identity == handoff.data_access.root_identity == str(package)
    assert handoff.migration_spec.sha256 == hashlib.sha256(handoff.migration_spec.content).hexdigest()
    assert handoff.data_access.sha256 == hashlib.sha256(handoff.data_access.content).hexdigest()


def test_s2_spec_is_held_once_and_only_the_authority_walks(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source", luid=None), source_rows(LIVE), LIVE_PROJECTION)
    original_read, original_walk, derive = Path.read_bytes, pfs.walk_package, pri.package_spec_facts
    reads, inputs = [], []

    def recorded(path: Path) -> bytes:
        if path.name == SPEC:
            reads.append(path)
        return original_read(path)

    def walked(root: Path):
        assert inspect.currentframe().f_back.f_globals["__name__"] == "package_filesystem", "consumer rewalked S1"
        return original_walk(root)

    def facts(spec: object) -> gate.PackageSpecFacts:
        inputs.append(copy.deepcopy(spec))
        return derive(spec)

    monkeypatch.setattr(Path, "read_bytes", recorded)
    monkeypatch.setattr(pfs, "walk_package", walked)
    monkeypatch.setattr(pri, "package_spec_facts", facts)
    result = pri.verify_phase1_role_identity([package])[0]
    assert result.is_start_ready, result.codes()
    assert reads == [package / SPEC] and len(inputs) == 1
    assert inputs[0]["data_sources"] == source_rows(LIVE)
    handoff = require_handoff(result.data_access_handoff(package))
    assert reads == [package / SPEC] and len(inputs) == 1, "handoff reparsed/reclassified the spec"
    assert handoff.facts.live_source_keys == (LIVE_KEY,)


@pytest.mark.parametrize(
    "projection", [LIVE_PROJECTION, {**LIVE_PROJECTION, "source_keys": [OTHER_KEY]}, LOCAL_PROJECTION]
)
def test_projection_discrimination_needs_only_new_handoffs(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, projection: dict
) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source", luid=None), source_rows(LIVE), projection)
    result = pri.verify_phase1_role_identity([package])[0]
    assert result.is_start_ready

    def forbidden(*_args: object, **_kwargs: object) -> None:
        pytest.fail("a held handoff read audit, reprobed, reclassified or reparsed the manifest")

    for name in (
        "_read_audit_trail",
        "_audit_entries",
        "assess_data_access",
        "read_data_access",
        "_classify_legs",
        "load_bundle",
    ):
        monkeypatch.setattr(gate, name, forbidden)
    monkeypatch.setattr(pri, "package_spec_facts", forbidden)
    monkeypatch.setattr(pfs, "parse_manifest_text", forbidden)
    monkeypatch.setattr(pfs, "declared_files", forbidden)
    handoff = require_handoff(result.data_access_handoff(package))
    parsed = gate.parse_data_access(handoff.data_access.content.decode("utf-8"))
    assert parsed.state == projection["state"], "the existing projection parser must still accept every control"
    assert handoff.facts.live_source_keys == (LIVE_KEY,)
    assert (parsed.source_keys == handoff.facts.live_source_keys) is (projection == LIVE_PROJECTION)
    assert handoff.facts.all_flat is False, "local-over-live must be distinguishable without reclassification"


@pytest.mark.parametrize("change", ["target", "case", "verified", "snapshot"])
def test_s2_snapshot_cannot_borrow_another_package(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, change: str
) -> None:
    first = with_data_access(datasource_package(tmp_path / "First", luid=None), source_rows(LIVE), LIVE_PROJECTION)
    second = with_data_access(datasource_package(tmp_path / "Second", luid=None), source_rows(FLAT))
    result, other = pri.verify_phase1_role_identity([first, second])
    target = first
    if change == "target":
        target = second
    elif change == "case":
        target = Path(str(first).swapcase())
    elif change == "verified":
        result = replace(result, verified=other.verified)
    else:
        result = replace(result, _data_access_snapshot=other._data_access_snapshot)

    def forbidden(*_args: object, **_kwargs: object) -> None:
        pytest.fail("a cross-root S2 handoff reached an S1 read")

    monkeypatch.setattr(pfs, "read_verified_member", forbidden)
    assert_refusal(result.data_access_handoff(target), "package_root_binding_invalid")


@pytest.mark.parametrize("declaration", [None, False, [], "DATA-ACCESS.JSON", "./data-access.json", "other.json"])
def test_s2_never_discovers_an_undeclared_projection(tmp_path: Path, declaration: object) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(FLAT))
    manifest = json.loads((package / "package-manifest.json").read_bytes())
    manifest["artifacts"]["data_access"] = declaration
    seal(package, **manifest)
    result = pri.verify_phase1_role_identity([package])[0]
    assert result.is_start_ready, "this PR must not add the final data-access role/fold to S2"
    assert_refusal(result.data_access_handoff(package), "package_member_not_verified")


@pytest.mark.parametrize("name", [SPEC, PROJECTION])
def test_post_s2_changes_refuse_instead_of_mixing_snapshots(tmp_path: Path, name: str) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(LIVE), LIVE_PROJECTION)
    result = pri.verify_phase1_role_identity([package])[0]
    path = package / name
    path.write_bytes(path.read_bytes() + b"\n")
    assert_refusal(result.data_access_handoff(package), "package_file_digest_mismatch")


@pytest.mark.parametrize("reverse", [False, True])
def test_provider_ordinals_and_owned_roles_keep_exact_snapshot_roots(tmp_path: Path, reverse: bool) -> None:
    first = with_data_access(
        datasource_package(tmp_path / "first", unit="Shared", luid=DS_LUID), source_rows(LIVE), LIVE_PROJECTION
    )
    second = with_data_access(datasource_package(tmp_path / "second", unit="Shared", luid=WB_LUID), source_rows(FLAT))
    consumer = with_data_access(
        workbook_package(
            tmp_path / "Consumer", published={"luid": DS_LUID}, binding="../../../first/fabric/Shared.SemanticModel"
        ),
        [{**PUBLISHED, "published_datasource": {"luid": DS_LUID}}],
    )
    owned = with_data_access(workbook_package(tmp_path / "Owned", unit="Owned"), source_rows(FLAT))
    roots = [first, second, consumer, owned]
    if reverse:
        roots.reverse()
    observations = tuple(pri.verify_s1(root) for root in reversed(roots))
    results = pri.verify_phase1_role_identity(roots, verified=observations)
    assert all(result.is_start_ready for result in results)
    for root, result in zip(roots, results, strict=True):
        held = require_handoff(result.data_access_handoff(root))
        assert held.migration_spec.root_identity == held.data_access.root_identity == str(root)
        assert held.migration_spec.content == (root / SPEC).read_bytes()
    provider, consuming, own = (results[roots.index(root)] for root in (first, consumer, owned))
    assert provider.topology == "published_provider" and own.topology == "owned_model"
    assert consuming.dependencies[0].provider_ordinal == roots.index(first)
    assert consuming.dependencies[0].provider_unit == "Shared"
    assert consuming.brief_policy.requested_scope == "report_only_shared_model"
    assert require_handoff(consuming.data_access_handoff(consumer)).facts.published_only
    assert own.source_handoff().root_identity == str(owned), "the existing package_source API must not change"


@pytest.mark.parametrize(
    "connections,keys,review,refusal",
    [
        ([FLAT], (), False, None),
        ([LIVE], (LIVE_KEY,), False, None),
        ([OTHER, LIVE], (LIVE_KEY, OTHER_KEY), False, None),
        ([REVIEW], (), True, None),
        ([LIVE, REVIEW], (LIVE_KEY,), True, None),
        ([LIVE, LIVE], (), False, "source-key-invalid"),
        ([{"class": "sqlserver", "powerbi_target": "live_source"}], (), False, "source-key-invalid"),
        ([{**LIVE, "server": True}], (), False, "spec-unreadable"),
        ([{**LIVE, "connections": "malformed"}], (), False, "spec-unreadable"),
    ],
)
def test_pure_spec_facts_reuse_canonical_leg_derivation(
    connections: list[dict], keys: tuple[str, ...], review: bool, refusal: str | None
) -> None:
    spec = {"data_sources": source_rows(*connections)}
    original = copy.deepcopy(spec)
    facts = gate.package_spec_facts(spec)
    assert (facts.live_source_keys, facts.has_review, facts.refusal_code) == (keys, review, refusal)
    assert facts.all_flat is (connections == [FLAT])
    assert not facts.published_only
    assert spec == original
    with pytest.raises(AttributeError):
        facts.has_review = False


@pytest.mark.parametrize("rows", [None, {}, False, "rows", [None], [False], [{"connection": []}], [{"fields": False}]])
def test_malformed_source_sets_preserve_authority_refusal(rows: object) -> None:
    facts = gate.package_spec_facts({"data_sources": rows})
    assert facts.refusal_code == "spec-unreadable"
    assert facts.live_source_keys == () and not facts.all_flat and not facts.published_only


def test_mixed_published_rows_are_not_published_only() -> None:
    published = gate.package_spec_facts({"data_sources": [copy.deepcopy(PUBLISHED)]})
    mixed = gate.package_spec_facts({"data_sources": [copy.deepcopy(PUBLISHED), *source_rows(LIVE)]})
    assert published.published_only and not published.direct_applicable
    assert published.live_source_keys == () and published.refusal_code is None
    assert not mixed.published_only, "a mixed-row handoff would let the future consumer borrow provider-only proof"
    assert not mixed.direct_applicable and not mixed.all_flat
    assert mixed.live_source_keys == (LIVE_KEY,)


@pytest.mark.parametrize(
    "extra",
    [
        {"connection": {**PUBLISHED["connection"], "connections": [LIVE]}},
        {"connection": {**PUBLISHED["connection"], "connections": []}},
        {"connection": {**PUBLISHED["connection"], "unknown": "sqlserver"}},
        {"connection": {**PUBLISHED["connection"], "mode": True}},
        {"connection": {"class": "SQLPROXY", "mode": "live"}},
        {"connections": [LIVE]},
        {"tables": [{"connection": LIVE}]},
        {"fields": [{"nested": {"connections": [LIVE]}}]},
        {"joins": [{"right": {"class": "sqlserver"}}]},
        {"fields": False},
        {"id": False},
        {"caption": []},
        {"published_datasource": {"luid": DS_LUID, "connection": LIVE}},
        {"published_datasource": {"luid": True}},
        {"published_datasource": None},
    ],
)
def test_malformed_or_nested_published_rows_never_gain_clean_applicability(extra: dict) -> None:
    facts = gate.package_spec_facts({"data_sources": [{**PUBLISHED, **extra}]})
    assert not facts.published_only and not facts.direct_applicable and not facts.all_flat


@pytest.mark.parametrize("raw", [b'{"source":{},"source":{}}', b'{"x":NaN}', b'{"x":1e999}', b"[]", b"\xff"])
def test_strict_spec_json_still_blocks_at_s2(tmp_path: Path, raw: bytes) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(LIVE), LIVE_PROJECTION)
    (package / SPEC).write_bytes(raw)
    seal(package, **json.loads((package / "package-manifest.json").read_bytes()))
    result = pri.verify_phase1_role_identity([package])[0]
    assert "identity_json_invalid" in result.blockers
    assert not result.is_start_ready
    assert_refusal(result.data_access_handoff(package), "package_member_not_verified")


@pytest.mark.parametrize(
    "raw,reason", [(b'{"state":0,"state":1}', "duplicate-key"), (b'{"x":NaN}', "nonfinite"), (b"[]", "not-an-object")]
)
def test_projection_stays_held_and_existing_parser_owns_strictness(tmp_path: Path, raw: bytes, reason: str) -> None:
    package = with_data_access(datasource_package(tmp_path / "Source"), source_rows(FLAT), raw)
    result = pri.verify_phase1_role_identity([package])[0]
    held = require_handoff(result.data_access_handoff(package))
    assert result.is_start_ready and held.data_access.content == raw, "no semantic consumer belongs in this PR"
    with pytest.raises(gate.DataAccessProjectionError) as caught:
        gate.parse_data_access(held.data_access.content.decode("utf-8"))
    assert caught.value.reason == reason


def test_new_handoffs_add_no_serialized_private_diagnostics(tmp_path: Path) -> None:
    private = {**LIVE, "server": "private-endpoint.example", "database": "private-database"}
    package = with_data_access(
        datasource_package(tmp_path / "PrivateRoot", luid=None), source_rows(private), LIVE_PROJECTION
    )
    result = pri.verify_phase1_role_identity([package])[0]
    handoff = require_handoff(result.data_access_handoff(package))
    assert set(result.as_dict()) == {
        "verdict",
        "unit",
        "kind",
        "topology",
        "roles",
        "source_identity",
        "dependencies",
        "blockers",
        "authorized_limitations",
    }
    serialized = json.dumps(result.as_dict()) + json.dumps(result.verified.integrity.as_dict()) + repr(handoff)
    for forbidden in (
        "private-endpoint",
        "private-database",
        "PrivateRoot",
        "data_sources",
        ".credential-gate",
    ):
        assert forbidden not in serialized
    assert str(tmp_path) not in serialized and repr(handoff.migration_spec.content) not in serialized
