/// Base import of the deterministic local CSV generated by scripts/make_refresh_fixture.py.
table Orders
	lineageTag: 5cd02347-50d8-44d2-a8ad-155fe90f0262

	measure 'Order Count' = COUNTROWS ( 'Orders' )
		formatString: #,##0
		lineageTag: 8ec652c2-f27d-4c04-89a2-a7cc355f0262

	measure 'Net Amount Total' = SUM ( 'Orders'[Net Amount] )
		formatString: $#,##0.00
		lineageTag: a54b2c13-7b27-4777-b774-c282a8f60262

	column OrderID
		dataType: string
		lineageTag: 82ab1f01-c045-4f9d-b174-32db98630262
		summarizeBy: none
		sourceColumn: OrderID

	column OrderDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 85ad1410-a233-49c2-858f-b29420470262
		summarizeBy: none
		sourceColumn: OrderDate

	column CustomerID
		dataType: string
		lineageTag: 34a03013-aeda-493b-bab8-c14b73120262
		summarizeBy: none
		sourceColumn: CustomerID

	column CustomerName
		dataType: string
		lineageTag: ed00da7b-dc81-4137-9b24-627984250262
		summarizeBy: none
		sourceColumn: CustomerName

	column Region
		dataType: string
		lineageTag: 50f90f48-76de-4e81-a694-d31155330262
		summarizeBy: none
		sourceColumn: Region

	column Country
		dataType: string
		lineageTag: e887fcec-bccd-499e-ac40-a871a0590262
		summarizeBy: none
		sourceColumn: Country

	column Category
		dataType: string
		lineageTag: b5e398f4-238b-453a-b645-d81d7f500262
		summarizeBy: none
		sourceColumn: Category

	column ProductID
		dataType: string
		lineageTag: 13b413fa-9a97-4eaf-959f-a132ce6f0262
		summarizeBy: none
		sourceColumn: ProductID

	column ShipMode
		dataType: string
		lineageTag: 848d4b8d-f559-4f90-b819-a08831f20262
		summarizeBy: none
		sourceColumn: ShipMode

	column Status
		dataType: string
		lineageTag: 6c05b1b1-a554-49c2-9b46-6734db140262
		summarizeBy: none
		sourceColumn: Status

	column Quantity
		dataType: int64
		formatString: #,##0
		lineageTag: b745268d-1cec-45ba-b431-12c006820262
		summarizeBy: sum
		sourceColumn: Quantity

	column UnitPrice
		dataType: decimal
		formatString: $#,##0.00
		lineageTag: 7cc2b662-7e93-4bcf-b887-e8d812dc0262
		summarizeBy: sum
		sourceColumn: UnitPrice

	column Discount
		dataType: decimal
		formatString: 0.00%
		lineageTag: 1dc30873-ed90-4242-a26f-39d159fc0262
		summarizeBy: sum
		sourceColumn: Discount

	column ShipDays
		dataType: int64
		formatString: #,##0
		lineageTag: 40fc6158-9cd1-49e0-a873-71402e550262
		summarizeBy: sum
		sourceColumn: ShipDays

	column Notes
		dataType: string
		lineageTag: b4bec544-e2da-498d-b46b-a455b8400262
		summarizeBy: none
		sourceColumn: Notes

	column 'Gross Amount'
		dataType: decimal
		formatString: $#,##0.00
		lineageTag: 38093192-4c0f-4c9d-aa9e-cb8e52ed0262
		summarizeBy: sum
		sourceColumn: Gross Amount

	column 'Net Amount'
		dataType: decimal
		formatString: $#,##0.00
		lineageTag: a428c072-b233-457d-8cd5-179ef60d0262
		summarizeBy: sum
		sourceColumn: Net Amount

	partition Orders = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(SourceFolder & "orders.csv"), [Delimiter=",", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {{"OrderID", type text}, {"OrderDate", type date}, {"CustomerID", type text}, {"CustomerName", type text}, {"Region", type text}, {"Country", type text}, {"Category", type text}, {"ProductID", type text}, {"ShipMode", type text}, {"Status", type text}, {"Quantity", Int64.Type}, {"UnitPrice", Currency.Type}, {"Discount", type number}, {"ShipDays", Int64.Type}, {"Notes", type text}}, "en-US"),
					#"Added Gross Amount" = Table.AddColumn(#"Changed Types", "Gross Amount", each [Quantity] * [UnitPrice], Currency.Type),
					#"Added Net Amount" = Table.AddColumn(#"Added Gross Amount", "Net Amount", each [Gross Amount] * (1 - [Discount]), Currency.Type)
				in
					#"Added Net Amount"

