/// Per-capita electricity by Region/Entity/Year (6,061 rows; 209 countries + 7 World-Bank regions; no 'World' total; 1985-2023). Tableau source 'Elec generation per capita + regions' (its vestigial Entity=Entity self-join is dropped). Also HOSTS the tree source's consumption calcs, which physically resolve to this same 'Elec generation' table via child=Entity. Backs 'Average per region' + the tree consumption marks.
table 'Elec Generation'
	lineageTag: fb9c9235-0ffe-5477-805c-69e4a9875a25

	/// Tableau tree calc [CY] = {MAX([Year])} (partition-less LOD grand-total max year). ALL()-scoped MAX. = 2023 in the current extract.
	measure 'CY' = CALCULATE(MAX('Elec Generation'[Year]), ALL('Elec Generation'))
		formatString: 0
		lineageTag: a913e7a2-339b-5f50-b8fa-64678f151072
		displayFolder: Consumption

	/// DIMENSION-FIXED LOD [CY Consumption] = SUM({FIXED [child]: SUM(IF [Year]=[CY] THEN [Per capita electricity - kWh] END)}). CY hoisted to a VAR (never a '[Col]=[Measure]' compact filter). In a child/Entity context this is that entity's per-capita at the latest year. GROUND TRUTH child='Norway' @CY=2023 -> 28056.230.
	measure 'CY Consumption' = VAR cy = CALCULATE(MAX('Elec Generation'[Year]), ALL('Elec Generation')) RETURN CALCULATE(SUM('Elec Generation'[Per capita electricity - kWh]), 'Elec Generation'[Year] = cy)
		formatString: #,##0.000
		lineageTag: 542cf68b-2461-5458-b68f-eac57a408ce6
		displayFolder: Consumption

	/// WINDOW table calc [Max year] = IF WINDOW_MAX(MAX([Year]))=MAX([Year]) THEN SUM([Per capita electricity - kWh]) END = show consumption only on each country's latest year. WINDOW_MAX over the per-country partition -> CALCULATE(MAX(Year), ALLEXCEPT(Entity)); compared to MAX(Year) in the current (Year-axis) context.
	measure 'Max year' = VAR emax = CALCULATE(MAX('Elec Generation'[Year]), ALLEXCEPT('Elec Generation', 'Elec Generation'[Entity])) RETURN IF(MAX('Elec Generation'[Year]) = emax, SUM('Elec Generation'[Per capita electricity - kWh]))
		formatString: #,##0.000
		lineageTag: bb866b23-8535-534b-be49-5784d3b6b329
		displayFolder: Consumption

	/// Tableau tree calc [Calculation2] (boolean) = [CY Consumption] > SUM({FIXED [Region]: AVG([Per capita electricity - kWh])}). {FIXED [Region]: AVG} -> CALCULATE(AVERAGE, ALLEXCEPT(Region)); measure hoisted, not a compact filter.
	measure 'Calculation2' = VAR regavg = CALCULATE(AVERAGE('Elec Generation'[Per capita electricity - kWh]), ALLEXCEPT('Elec Generation', 'Elec Generation'[Region])) RETURN [CY Consumption] > regavg
		lineageTag: e65fea16-53d2-5796-9ce7-8295e1dca653
		displayFolder: Consumption

	/// Tableau [Global avg in 2022] = literal constant 3616.7 (equals the FNR 'World' entity's 2022 total per-capita 3616.692). A fixed reference-line value.
	measure 'Global avg in 2022' = 3616.7
		formatString: #,##0.0
		lineageTag: 2771c411-5af1-53dc-8d50-7725dfbf7a0c
		displayFolder: Consumption

	/// Tableau [Ratio] = AVG([Per capita electricity - kWh]) / AVG([Global avg in 2022]); the constant AVG is itself 3616.7. Each country/region's average per-capita vs the world 2022 benchmark.
	measure 'Ratio' = DIVIDE(AVERAGE('Elec Generation'[Per capita electricity - kWh]), [Global avg in 2022])
		formatString: 0.00
		lineageTag: a7e6f9a6-29a7-53f0-ba40-68c976fd4cdc
		displayFolder: Consumption

	column 'Region'
		dataType: string
		lineageTag: 7ae8c59f-ab8c-570e-8dd8-bfca04e87259
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Income group'
		dataType: string
		lineageTag: 30c7997a-f596-5192-93a5-1deba25bd97a
		summarizeBy: none
		sourceColumn: Income group

		annotation SummarizationSetBy = Automatic

	column 'Entity'
		dataType: string
		lineageTag: 2ec674e8-47f0-5aa0-8d3f-3f43c845bc86
		summarizeBy: none
		sourceColumn: Entity

		annotation SummarizationSetBy = Automatic

	column 'Code'
		dataType: string
		lineageTag: aaf3f841-5189-5e76-8c9f-e8a730ea7bca
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column 'Year'
		dataType: int64
		lineageTag: 9e239ae9-05cd-5115-9455-6806aba1569b
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Per capita electricity - kWh'
		dataType: double
		lineageTag: c1aa7ef5-fdf8-5d4b-9fbf-8bcaa9e56ff0
		summarizeBy: sum
		sourceColumn: Per capita electricity - kWh

		annotation SummarizationSetBy = Automatic

	/// Tableau tree calc [Elec gen at 2022] = IF [Year]=2022 THEN [Per capita electricity - kWh] END. Relocated here (references Elec generation columns).
	column 'Elec gen at 2022' = IF('Elec Generation'[Year] = 2022, 'Elec Generation'[Per capita electricity - kWh])
		dataType: double
		lineageTag: 4778356b-fe01-503a-8c56-60264db88c78
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Tableau tree calc [Max year (copy)] = IF [Year]=[CY] THEN [Per capita electricity - kWh] END, where [CY]={MAX([Year])} (grand-total max year). Relocated row-level column.
	column 'Consumption at CY' = VAR cy = CALCULATE(MAX('Elec Generation'[Year]), ALL('Elec Generation')) RETURN IF('Elec Generation'[Year] = cy, 'Elec Generation'[Per capita electricity - kWh])
		dataType: double
		lineageTag: b45c710e-6431-50b2-99aa-098e8b127b7a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// DIMENSION-FIXED LOD [Region and country count] = [Region] + newlines + STR({FIXED [Region]: COUNTD([Entity])}) + ' countries'.
	column 'Region and country count' = 'Elec Generation'[Region] & UNICHAR(10) & UNICHAR(10) & CALCULATE(DISTINCTCOUNT('Elec Generation'[Entity]), ALLEXCEPT('Elec Generation', 'Elec Generation'[Region])) & " countries"
		dataType: string
		lineageTag: d45cd6a1-1d6e-5b9d-adb4-a19c14a67ebf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Elec Generation' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "ds.elec_generation_per_capita_regions.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Region", type text}, {"Income group", type text}, {"Entity", type text}, {"Code", type text}, {"Year", Int64.Type}, {"Per capita electricity - kWh", type number}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
