/// OWID per-capita electricity by Entity x Year with fossil/nuclear/renewable kWh columns (5,956 rows; 223 entities incl. 'World'; 1985-2023). Tableau source 'per-capita-electricity-fossil-nuclear-renewables'. Backs the 3 'World ... only' worksheets.
table 'Per Capita FNR'
	lineageTag: d9130044-641f-5b71-92dc-4653757b1ff7

	column 'Entity'
		dataType: string
		lineageTag: b1c11cea-d41b-5640-ae9a-e1d9f081336e
		summarizeBy: none
		sourceColumn: Entity

		annotation SummarizationSetBy = Automatic

	column 'Code'
		dataType: string
		lineageTag: a8d7814f-2922-5775-aa9c-57ae83bec069
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column 'Year'
		dataType: int64
		lineageTag: 983ca501-a19b-5163-a19c-505eb34d0337
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Fossil fuel electricity per capita - kWh'
		dataType: double
		lineageTag: 649ad351-ca1d-5046-a5c9-2ae7c53908a5
		summarizeBy: sum
		sourceColumn: Fossil fuel electricity per capita - kWh (adapted for visualization of chart per-capita-electricity-fossil-nuclear-renewables)

		annotation SummarizationSetBy = Automatic

	column 'Nuclear electricity per capita - kWh'
		dataType: double
		lineageTag: f8aad89f-52ea-5113-845f-63b0cbf59bfe
		summarizeBy: sum
		sourceColumn: Nuclear electricity per capita - kWh (adapted for visualization of chart per-capita-electricity-fossil-nuclear-renewables)

		annotation SummarizationSetBy = Automatic

	column 'Renewable electricity per capita - kWh'
		dataType: double
		lineageTag: cb22ae08-1e4a-5369-ba92-5630c5681f28
		summarizeBy: sum
		sourceColumn: Renewable electricity per capita - kWh (adapted for visualization of chart per-capita-electricity-fossil-nuclear-renewables)

		annotation SummarizationSetBy = Automatic

	/// Tableau [FF%] = FF/(FF+Nuc+Ren), a row-level ratio. Row-level calc column (no top-level aggregation). Worksheet 'World FF only' shows SUM at one-row-per-year World grain -> summarizeBy=sum reproduces it. GROUND TRUTH World 2022 = 0.61432.
	column 'FF%' = DIVIDE('Per Capita FNR'[Fossil fuel electricity per capita - kWh], 'Per Capita FNR'[Fossil fuel electricity per capita - kWh] + 'Per Capita FNR'[Nuclear electricity per capita - kWh] + 'Per Capita FNR'[Renewable electricity per capita - kWh])
		dataType: double
		lineageTag: c90cfc23-698c-5267-95b0-7bd8a7184495
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Tableau [Nuclear%] = Nuc/(FF+Nuc+Ren). GROUND TRUTH World 2022 = 0.09152.
	column 'Nuclear%' = DIVIDE('Per Capita FNR'[Nuclear electricity per capita - kWh], 'Per Capita FNR'[Fossil fuel electricity per capita - kWh] + 'Per Capita FNR'[Nuclear electricity per capita - kWh] + 'Per Capita FNR'[Renewable electricity per capita - kWh])
		dataType: double
		lineageTag: 65325d45-76ea-5089-b9c5-71f1933d1f71
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Tableau [Renewables %] (internal 'Nuclear% (copy)') = Ren/(FF+Nuc+Ren). GROUND TRUTH World 2022 = 0.29416.
	column 'Renewables %' = DIVIDE('Per Capita FNR'[Renewable electricity per capita - kWh], 'Per Capita FNR'[Fossil fuel electricity per capita - kWh] + 'Per Capita FNR'[Nuclear electricity per capita - kWh] + 'Per Capita FNR'[Renewable electricity per capita - kWh])
		dataType: double
		lineageTag: 3182c641-d445-5a1e-ba9c-1657f27b58d5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Per Capita FNR' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "ds.per_capita_electricity_fossil_nuclear_renewables.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Entity", type text}, {"Code", type text}, {"Year", Int64.Type}, {"Fossil fuel electricity per capita - kWh (adapted for visualization of chart per-capita-electricity-fossil-nuclear-renewables)", type number}, {"Nuclear electricity per capita - kWh (adapted for visualization of chart per-capita-electricity-fossil-nuclear-renewables)", type number}, {"Renewable electricity per capita - kWh (adapted for visualization of chart per-capita-electricity-fossil-nuclear-renewables)", type number}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
