/// Resume-page fun facts / social decorations (5 rows: Piano, Singing, Theater, Ultimate Frisbee, White House). Backs decorative resume worksheets; Fact is carried as a label and is not visually bound. Source: Tableau 'Sheet1 (Fun Facts_Resume)'.
table 'Fun Facts Resume'
	lineageTag: 6cffbab1-dc2b-5b25-a8f3-70d2db34b372

	/// Row count of 'Fun Facts Resume' (each row = one resume fun fact). Hidden technical measure; renamed from Tableau's auto-generated 'Number of Records' so measure names stay unique model-wide.
	measure 'Fun Facts Resume Row Count' = COUNTROWS('Fun Facts Resume')
		formatString: #,##0
		isHidden
		displayFolder: Row Counts
		lineageTag: e6e72507-3a06-5a9d-8edc-eea3f15a722f

	/// Row identifier (1 to 5). Key of this table.
	column ID
		dataType: int64
		lineageTag: cdbb655e-2223-5dda-b78c-83e351c6c4cf
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	/// Fun-fact / hobby label. One of: Piano, Singing, Theater, Ultimate Frisbee, White House. Carried for reference; not visually bound in the resume worksheets.
	column Fact
		dataType: string
		lineageTag: 1ea5d45c-8601-5ffb-83e5-60fde953211c
		summarizeBy: none
		sourceColumn: Fact

		annotation SummarizationSetBy = Automatic

	/// Placeholder text ('lorem ipsum'); no real content in the source workbook.
	column Description
		dataType: string
		lineageTag: 3048324c-6eed-5aff-8159-e19a422436c4
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	/// Relative weight used to size the fun-fact mark (integer; 3 or 5). Additive.
	column 'Fact Sum'
		dataType: int64
		lineageTag: a918c9fa-be7b-5c61-96e0-b3a8a971f49f
		summarizeBy: sum
		sourceColumn: Fact Sum

		annotation SummarizationSetBy = Automatic

	partition 'Fun Facts Resume' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "ds.sheet1_fun_facts_resume.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"ID", Int64.Type}, {"Fact", type text}, {"Description", type text}, {"Fact Sum", Int64.Type}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

