/// Academic major and minors (3 rows: Economics = Major; Data Analysis and Statistics = Minor). Size drives bubble area in the 'Bubbles' worksheet. Source: Tableau 'Sheet1 (Maj_Min_Resume)'.
table 'Major Minor Resume'
	lineageTag: 413087ee-38b2-593c-b546-7b5c55059d1f

	/// Row count of 'Major Minor Resume' (each row = one major/minor discipline). Hidden technical measure; renamed from Tableau's auto-generated 'Number of Records' so measure names stay unique model-wide.
	measure 'Major Minor Resume Row Count' = COUNTROWS('Major Minor Resume')
		formatString: #,##0
		isHidden
		displayFolder: Row Counts
		lineageTag: 5034c699-b3e2-5e9d-b4f7-0c929e096aa0

	/// Academic discipline. One of: Economics, Data Analysis, Statistics.
	column Title
		dataType: string
		lineageTag: 722a1115-0a06-5a70-afc6-c83c6ef79168
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	/// Display order / position of the discipline (1 to 3). Not additive.
	column Number
		dataType: int64
		lineageTag: 974359e7-9e56-593f-a846-5664af657515
		summarizeBy: none
		sourceColumn: Number

		annotation SummarizationSetBy = Automatic

	/// Whether the discipline is the major or a minor. One of: Major, Minor.
	column Type
		dataType: string
		lineageTag: f84f3c2a-caaf-5333-b5ed-d05bfa35c34f
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	/// Relative bubble size in the 'Bubbles' worksheet (Major = 3, Minor = 1). Additive.
	column Size
		dataType: int64
		lineageTag: 5db215b6-db40-5a82-aef4-2e70280c9ea2
		summarizeBy: sum
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	partition 'Major Minor Resume' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "ds.sheet1_maj_min_resume.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Title", type text}, {"Number", Int64.Type}, {"Type", type text}, {"Size", Int64.Type}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

