"""
purpose: Build an HONESTLY-LABELED SYNTHETIC reference image when no real Tableau capture exists - a
         small HTML/CSS bar chart rendered from REAL queried data (never fabricated numbers),
         screenshotted via Playwright, written into reference/manifest.json using the same schema as
         capture_tableau_reference.py (see docs/reference-capture.md).
usage:   python scripts/build_synthetic_reference.py <slug_dir> --data-file <rows.json>
             --title "Billing by Customer" [--dashboard-name "Overview"] [--oracle-source "..."]
             [--unit "$"] [--force]

         rows.json shape: [{"label": "...", "value": 123.45}, ...] - a list of {label, value} pairs
         sourced from a REAL query (e.g. a live DAX EVALUATE against an already-refreshed model, or a
         warehouse query result). Pass it as a FILE, not inline JSON: this repo already hit a real
         PowerShell double-escaping failure passing JSON inline to another CLI - a file sidesteps
         that class of bug entirely. This script does not query anything itself: decoupling "get
         real numbers" from "render + screenshot" keeps it simple and avoids yet another place a
         data-source credential could leak.

THIS IS NOT A SUBSTITUTE for a real Tableau capture. It exists only to give pbi-report-builder /
pbi-migration-validator SOMETHING CONCRETE to look at (real numbers, not zero context) when
capture_tableau_reference.py has correctly failed closed (no public URL, no Server, no manual
screenshot) - most commonly this repo's own _probe-lab/ credential-gate test fixtures, whose .twb is
a synthetic skeleton generated by probe_lab.py (not downloaded from anywhere), so no real Tableau
dashboard exists to screenshot in the first place.

Deliberately NOT wired into capture_tableau_reference.py's provider chain: that pipeline is designed
to FAIL CLOSED when no real reference exists (see docs/reference-capture.md "Default = fail closed"),
and a synthetic chart of queried numbers is not a valid substitute for "we have no image of the
source dashboard" - silently offering one there would blur exactly the guarantee that design
protects. This stays a separate, explicitly-invoked tool.

Provider is stamped "synthetic_data_chart" with capabilities=[] (no layout_grade, no text_readable,
no validation_grade - no claim of any kind about the ORIGINAL Tableau look) and a "synthetic": true
flag on every state record, so no consumer can mistake this for real capture output even on a
partial read of the manifest. The real queried rows are embedded in numeric_oracle (they ARE real,
just not a picture of anything) and a visible disclaimer is baked into the rendered PNG itself, so
the image is unambiguous even viewed alone, outside its manifest.
"""

from __future__ import annotations

import argparse
import json
import logging
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# Reuse the real capture script's provenance helpers instead of duplicating them.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from capture_tableau_reference import (  # noqa: E402  pylint: disable=wrong-import-position
    _is_valid_png,
    _png_dimensions,
    _sha256,
    _slug_for,
    _utcnow,
)

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger("build-synthetic-reference")

PROVIDER_SYNTHETIC = "synthetic_data_chart"
DISCLAIMER = "SYNTHETIC REFERENCE \u2014 not a Tableau capture. Rendered from real queried data for orientation only."

# Playwright capture of a LOCAL html file (not a remote URL) - same technique as
# capture_tableau_reference.py's _CAPTURE_JS, minus the consent-banner/network waits a live site needs.
_CAPTURE_JS = r"""
const { chromium } = require("playwright");
(async () => {
  const [url, out] = [process.argv[2], process.argv[3]];
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 900, height: 200 }, deviceScaleFactor: 2 });
  try {
    await page.goto(url, { waitUntil: "load", timeout: 30000 });
    await page.screenshot({ path: out, fullPage: true });
    console.log("OK");
  } catch (e) {
    console.log("ERR " + e.message);
    process.exitCode = 2;
  } finally {
    await browser.close();
  }
})();
"""

_HTML_TEMPLATE = """<!doctype html>
<html><head><meta charset="utf-8"><style>
  body {{ font-family: -apple-system, Segoe UI, Arial, sans-serif; margin: 0; padding: 28px 32px;
          background: #ffffff; color: #1a1a1a; width: 836px; box-sizing: border-box; }}
  .eyebrow {{ font-size: 12px; letter-spacing: 0.08em; text-transform: uppercase; color: #6b6b6b;
              margin: 0 0 4px; }}
  h1 {{ font-size: 22px; margin: 0 0 20px; }}
  .row {{ display: flex; align-items: center; margin-bottom: 10px; }}
  .label {{ width: 190px; flex: 0 0 190px; text-align: right; padding-right: 12px; font-size: 13px;
            white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }}
  .barwrap {{ flex: 1; background: #f0f0f0; border-radius: 3px; height: 22px; position: relative; }}
  .bar {{ background: #f2c811; height: 100%; border-radius: 3px; }}
  .value {{ position: absolute; left: calc(100% + 8px); top: 0; font-size: 12px; white-space: nowrap; }}
  .disclaimer {{ margin-top: 22px; padding: 10px 14px; background: #fff4e5; border: 1px solid #e8a33d;
                 border-radius: 4px; font-size: 12px; color: #7a4a00; }}
</style></head>
<body>
  <p class="eyebrow">{dashboard_name}</p>
  <h1>{title}</h1>
  {rows_html}
  <div class="disclaimer">{disclaimer}</div>
</body></html>
"""


def _row_html(label: str, value: float, max_value: float, unit: str) -> str:
    pct = 0.0 if max_value <= 0 else max(1.0, 100.0 * value / max_value)
    formatted = f"{unit}{value:,.2f}" if unit else f"{value:,.2f}"
    safe_label = label.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return (
        f'<div class="row"><div class="label">{safe_label}</div>'
        f'<div class="barwrap"><div class="bar" style="width:{pct:.2f}%"></div>'
        f'<span class="value">{formatted}</span></div></div>'
    )


def render_html(title: str, dashboard_name: str, rows: list[dict], unit: str) -> str:
    """Build the standalone HTML page for a sorted set of {label, value} rows."""
    ordered = sorted(rows, key=lambda r: r["value"], reverse=True)
    max_value = max((r["value"] for r in ordered), default=0.0)
    rows_html = "\n  ".join(_row_html(r["label"], r["value"], max_value, unit) for r in ordered)
    return _HTML_TEMPLATE.format(dashboard_name=dashboard_name, title=title, rows_html=rows_html, disclaimer=DISCLAIMER)


def screenshot_html(html: str, out_path: Path) -> bool:
    """Render `html` to `out_path` via headless Chromium. Returns False on any capture failure."""
    node = shutil.which("node")
    if not node:
        log.error("node not found on PATH - cannot run the Playwright capture")
        return False
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", suffix=".html", delete=False, encoding="utf-8") as tmp_html:
        tmp_html.write(html)
        html_path = Path(tmp_html.name)
    with tempfile.NamedTemporaryFile("w", suffix=".js", delete=False, encoding="utf-8") as tmp_js:
        tmp_js.write(_CAPTURE_JS)
        js_path = tmp_js.name
    try:
        file_url = "file:///" + str(html_path.resolve()).replace("\\", "/")
        proc = subprocess.run(
            [node, js_path, file_url, str(out_path)],
            capture_output=True,
            text=True,
            timeout=60,
            check=False,
        )
        log.info("playwright: %s", (proc.stdout or proc.stderr).strip()[:200])
    except subprocess.TimeoutExpired:
        log.error("playwright capture timed out")
        return False
    finally:
        Path(js_path).unlink(missing_ok=True)
        html_path.unlink(missing_ok=True)
    return _is_valid_png(out_path)


def _load_rows(data_file: Path) -> list[dict]:
    try:
        raw = json.loads(data_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"could not read/parse {data_file}: {exc}") from exc
    if not isinstance(raw, list) or not raw:
        raise SystemExit(f"{data_file} must contain a non-empty JSON array of {{label, value}} objects")
    rows = []
    for i, item in enumerate(raw):
        if not isinstance(item, dict) or "label" not in item or "value" not in item:
            raise SystemExit(f"{data_file}[{i}] must be an object with 'label' and 'value' keys")
        rows.append({"label": str(item["label"]), "value": float(item["value"])})
    return rows


def _existing_manifest(reference_dir: Path) -> dict | None:
    manifest = reference_dir / "manifest.json"
    if not manifest.is_file():
        return None
    try:
        return json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def build(args: argparse.Namespace) -> int:
    """Render, screenshot, and write the honestly-labeled synthetic manifest. Returns an exit code."""
    slug_dir = Path(args.slug_dir).resolve()
    if not slug_dir.is_dir():
        log.error("not a directory: %s", slug_dir)
        return 2
    reference_dir = slug_dir / "reference"

    existing = _existing_manifest(reference_dir)
    if existing and existing.get("dashboards") and not args.force:
        log.error(
            "%s already has %d real dashboard state(s) - refusing to overwrite a real capture with a "
            "synthetic one. Pass --force if you really mean to replace it.",
            reference_dir / "manifest.json",
            len(existing["dashboards"]),
        )
        return 1

    rows = _load_rows(Path(args.data_file))
    html = render_html(args.title, args.dashboard_name, rows, args.unit)
    image = reference_dir / _slug_for(args.dashboard_name) / "synthetic.png"
    if not screenshot_html(html, image):
        log.error("synthetic capture failed - no valid PNG produced")
        return 1

    manifest = {
        "captured_at": _utcnow(),
        "source_workbook_sha256": None,
        "dashboards": [
            {
                "name": args.dashboard_name,
                "states": [
                    {
                        "state_slug": "default",
                        "state": {},
                        "image": str(image.relative_to(reference_dir)).replace("\\", "/"),
                        "provider": PROVIDER_SYNTHETIC,
                        "capabilities": [],
                        "synthetic": True,
                        "dimensions": _png_dimensions(image) or {},
                        "sha256": _sha256(image),
                        "numeric_oracle": {
                            "source": args.oracle_source,
                            "rows": sorted(rows, key=lambda r: r["value"], reverse=True),
                        },
                        "note": (
                            "SYNTHETIC placeholder: a generic bar chart rendered from real queried "
                            "data, NOT a capture of the Tableau original. capabilities is "
                            "intentionally empty - no layout or visual-fidelity claim. Use only for "
                            "orientation ('something concrete to look at'), never for figure-by-"
                            "figure visual grading against Tableau."
                        ),
                    }
                ],
            }
        ],
    }
    manifest_path = reference_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    log.info("wrote %s (synthetic, %d row(s))", manifest_path, len(rows))
    return 0


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("slug_dir", help="path to a migration/probe folder, e.g. _probe-lab/variant-a")
    parser.add_argument("--data-file", required=True, help='JSON file: [{"label": ..., "value": ...}, ...]')
    parser.add_argument("--title", required=True, help="chart title (e.g. the Tableau worksheet name)")
    parser.add_argument("--dashboard-name", default="dashboard", help="dashboard name for the manifest")
    parser.add_argument("--oracle-source", default="caller-supplied data file", help="how the numbers were obtained")
    parser.add_argument("--unit", default="", help="prefix for values, e.g. '$'")
    parser.add_argument("--force", action="store_true", help="overwrite an existing manifest with real captures")
    args = parser.parse_args(argv)
    return build(args)


if __name__ == "__main__":
    sys.exit(main())
