"""
purpose: capture the Tableau trial site as a manifest + local assets, and re-apply it to an empty
         site - so a hand-built test estate survives a trial expiring, a tenant reset, or a colleague
         needing the same fixtures.
usage:   python scripts/provision_tableau_estate.py capture --out _runs/tableau-estate
         python scripts/provision_tableau_estate.py apply   --manifest _runs/tableau-estate/manifest.json --dry-run
         python scripts/provision_tableau_estate.py apply   --manifest _runs/tableau-estate/manifest.json

Why this exists
---------------
The estate on the trial site is hand-built and deliberately hostile: 35 projects nested up to 11
deep, names chosen to break path handling (`R/D`, `R+D`, `Trailing dot.`, `Ventes francaises`),
live Snowflake/Databricks published datasources, entitlement groups for RLS, and a datasource whose
whole purpose is to have NO embedded credentials. None of that is reproducible from the repo: the
pipeline only ever reads FROM Tableau and writes TO Fabric. If the trial lapses, the fixtures are
gone and every live-source test loses its subject.

Three things this encodes that are easy to get wrong
----------------------------------------------------
1. **Projects are identified by PATH, never by LUID.** Every LUID changes on re-apply, so a manifest
   keyed by LUID is write-only. Paths also make the parent/child ordering explicit: `apply` creates
   them shallowest-first, because a child cannot name a parent that does not exist yet.
2. **Datasources must land before the workbooks that bind to them.** A workbook published first
   silently rebinds to nothing, which is exactly the empty-report failure the migration pipeline
   spends so much effort detecting downstream. Ordering is not cosmetic.
3. **Some content is Tableau's, not ours, and must NOT be republished.** `Admin Insights` and its
   nine datasources are generated by Tableau Cloud itself; `Samples` ships with the site. Attempting
   to recreate them either fails outright or shadows the real ones. They are captured for
   completeness and skipped on apply, flagged `tableau_managed`.

Deliberate non-goals
--------------------
Permissions and group MEMBERSHIP are not reproduced. Groups are created (they are needed for the RLS
fixtures to bind), but who belongs to them, and every permission rule, is left alone: on a fresh site
the user LUIDs differ, and a half-correct permission model is more dangerous than an obviously absent
one. `apply` says so on completion rather than letting you assume it was handled.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

try:
    import tableauserverclient as tsc
except ImportError:  # pragma: no cover - dependency is optional until the script is actually run
    tsc = None

from tableau_env import pat_secret, require, resolve_env, server_url  # noqa: E402  # pylint: disable=wrong-import-position

# Content Tableau Cloud provisions itself. Capturing it is useful (it explains what is on the site);
# recreating it is wrong - the originals already exist on any new site.
TABLEAU_MANAGED_PROJECTS = frozenset({"Admin Insights", "Samples", "default", "External Assets Default Project"})
BUILTIN_GROUPS = frozenset({"All Users"})

# A datasource whose fixture value IS the missing credential. Publishing it WITH one destroys the
# thing it exists to test, so the heuristic below defaults it to "do not embed".
_NO_CREDENTIAL_MARKERS = ("no embedded credential", "no credential")

# Projects whose emptiness is the fixture. Seeding these would destroy what they test.
# Keyed on `show_path` output, so the separator here must match it.
KEEP_EMPTY = frozenset({"ZZ Migration Torture > Empty On Purpose"})


@dataclass
class ProjectRecord:
    """A project keyed by its ancestry SEGMENTS, which is what survives a re-apply."""

    path: list[str]
    name: str
    description: str = ""
    tableau_managed: bool = False

    @property
    def depth(self) -> int:
        """Nesting level, used to order creation shallowest-first."""
        return len(self.path)

    @property
    def parent_path(self) -> list[str]:
        """Ancestry of this project's parent; empty for a top-level project."""
        return self.path[:-1]


@dataclass
class ContentRecord:  # pylint: disable=too-many-instance-attributes
    """A published datasource or workbook, plus where its downloaded file landed."""

    name: str
    project_path: list[str]
    kind: str
    content_type: str = ""
    filename: str = ""
    embed_credentials: bool = True
    tableau_managed: bool = False
    notes: list[str] = field(default_factory=list)


def project_path_of(project: Any, by_id: dict[str, Any]) -> tuple[str, ...]:
    """Build the ancestry as SEGMENTS, guarding against a cyclic parent chain.

    Segments, not a joined string, because a project may legitimately be named `R/D`. Joining on `/`
    makes that indistinguishable from a project `D` nested inside `R`, and the trial site has exactly
    that fixture - it caught this function's first version, which mislabelled the seed for `R/D` as
    belonging to a project called `D`.
    """
    parts: list[str] = []
    seen: set[str] = set()
    node = project
    while node is not None:
        if node.id in seen:
            parts.insert(0, f"<cycle:{node.name}>")
            break
        seen.add(node.id)
        parts.insert(0, node.name)
        node = by_id.get(node.parent_id) if node.parent_id else None
    return tuple(parts)


def show_path(segments: tuple[str, ...] | list[str]) -> str:
    """Human-readable path. Display only - never parse this back into segments."""
    return " > ".join(segments)


def _managed(segments: tuple[str, ...] | list[str]) -> bool:
    return bool(segments) and segments[0] in TABLEAU_MANAGED_PROJECTS


def _safe_filename(name: str, suffix: str) -> str:
    """Filesystem-safe name. Collisions are resolved by the caller, not by hoping they don't happen."""
    keep = "".join(c if (c.isalnum() or c in " -_()") else "_" for c in name).strip()
    return f"{keep or 'unnamed'}{suffix}"


def _sign_in(env: dict[str, str]) -> Any:
    if tsc is None:
        raise SystemExit("tableauserverclient is not installed - run: uv pip install tableauserverclient")
    auth = tsc.PersonalAccessTokenAuth(env["TABLEAU_PAT_NAME"], pat_secret(env), site_id=env.get("TABLEAU_SITE", ""))
    return tsc.Server(server_url(env), use_server_version=True), auth


def _unique(base: str, taken: set[str]) -> str:
    if base not in taken:
        taken.add(base)
        return base
    stem, dot, ext = base.rpartition(".")
    for n in range(2, 1000):
        candidate = f"{stem} ({n}){dot}{ext}"
        if candidate not in taken:
            taken.add(candidate)
            return candidate
    raise RuntimeError(f"could not find a unique filename for {base!r}")


def capture(  # pylint: disable=too-many-locals
    out_dir: Path, env: dict[str, str], *, include_extract: bool, download: bool
) -> dict[str, Any]:
    """Enumerate the live site, download each asset, and write a re-appliable manifest."""
    server, auth = _sign_in(env)
    assets = out_dir / "assets"
    assets.mkdir(parents=True, exist_ok=True)
    taken: set[str] = set()

    with server.auth.sign_in(auth):
        raw_projects = list(tsc.Pager(server.projects))
        by_id = {p.id: p for p in raw_projects}
        projects = sorted(
            (
                ProjectRecord(
                    path=list(path := project_path_of(p, by_id)),
                    name=p.name,
                    description=p.description or "",
                    tableau_managed=_managed(path),
                )
                for p in raw_projects
            ),
            key=lambda r: (r.depth, r.path),
        )

        groups = [g.name for g in tsc.Pager(server.groups) if g.name not in BUILTIN_GROUPS]

        content: list[ContentRecord] = []
        for kind, endpoint in (("datasource", server.datasources), ("workbook", server.workbooks)):
            for item in tsc.Pager(endpoint):
                segments = (
                    project_path_of(by_id[item.project_id], by_id) if item.project_id in by_id else (item.project_name,)
                )
                managed = _managed(segments)
                rec = ContentRecord(
                    name=item.name,
                    project_path=list(segments),
                    kind=kind,
                    content_type=getattr(item, "datasource_type", "") or "",
                    embed_credentials=not any(m in item.name.lower() for m in _NO_CREDENTIAL_MARKERS),
                    tableau_managed=managed,
                )
                if not rec.embed_credentials:
                    rec.notes.append("heuristic from name: fixture deliberately has NO embedded credentials")
                if download and not managed:
                    try:
                        rec.filename = _download_asset(endpoint, item, assets, taken, include_extract)
                    except Exception as exc:  # pylint: disable=broad-except
                        rec.notes.append(f"download failed: {type(exc).__name__}: {exc}")
                        rec.filename = ""
                content.append(rec)

    manifest = {
        "schema_version": "1.0",
        "site": env.get("TABLEAU_SITE", ""),
        "server_url": server_url(env),
        "include_extract": include_extract,
        "projects": [asdict(p) for p in projects],
        "groups": groups,
        "content": [asdict(c) for c in sorted(content, key=lambda c: (c.kind, c.project_path, c.name))],
    }
    return manifest


def _download_asset(endpoint: Any, item: Any, assets: Path, taken: set[str], include_extract: bool) -> str:
    """Download one asset and return the filename actually stored.

    The extension is taken from what Tableau RETURNS, never guessed. Two measured reasons: TSC
    appends its own suffix to whatever `filepath` you hand it (asking for `X.twbx` yields
    `X.twbx.twbx`), and a workbook with no packaged data comes back as `.twb`, not `.twbx`. Guessing
    either produced a manifest whose filenames did not exist on disk - `apply` then reported every
    one of them as a missing asset.
    """
    written = Path(endpoint.download(item.id, filepath=str(assets), include_extract=include_extract))
    final = assets / _unique(_safe_filename(item.name, written.suffix), taken)
    if written.resolve() != final.resolve():
        written.replace(final)
    return final.name


def _credentials_for(content_type: str, env: dict[str, str]) -> Any:
    """Map a connector to the credential this repo's `.env` already holds, or None if unknown."""
    if tsc is None:
        return None
    if content_type == "snowflake" and env.get("TABLEAU_SF_USER") and env.get("TABLEAU_SF_PASSWORD"):
        return tsc.ConnectionCredentials(env["TABLEAU_SF_USER"], env["TABLEAU_SF_PASSWORD"], embed=True)
    if content_type == "databricks" and env.get("TABLEAU_DBX_TOKEN"):
        return tsc.ConnectionCredentials("token", env["TABLEAU_DBX_TOKEN"], embed=True)
    return None


def apply_manifest(  # pylint: disable=too-many-branches,too-many-locals,too-many-statements
    manifest: dict[str, Any],
    assets: Path,
    env: dict[str, str],
    *,
    dry_run: bool,
    overwrite: bool,
) -> int:
    """Recreate projects, groups, datasources and workbooks. Returns a process exit code."""
    server, auth = _sign_in(env)
    planned: list[str] = []
    problems: list[str] = []

    with server.auth.sign_in(auth):
        all_projects = list(tsc.Pager(server.projects))
        by_id = {p.id: p for p in all_projects}
        path_to_id = {project_path_of(p, by_id): p.id for p in all_projects}

        # Shallowest first: a child cannot name a parent that does not exist yet.
        for rec in sorted(manifest["projects"], key=lambda r: (len(r["path"]), r["path"])):
            segments = tuple(rec["path"])
            if rec["tableau_managed"]:
                continue
            if segments in path_to_id:
                planned.append(f"  = project exists   {show_path(segments)}")
                continue
            parent = segments[:-1]
            parent_id = path_to_id.get(parent)
            if parent and parent_id is None:
                problems.append(f"project {show_path(segments)!r}: parent {show_path(parent)!r} missing")
                continue
            planned.append(f"  + project CREATE   {show_path(segments)}")
            if not dry_run:
                item = tsc.ProjectItem(name=rec["name"], description=rec["description"] or None, parent_id=parent_id)
                path_to_id[segments] = server.projects.create(item).id

        existing_groups = {g.name for g in tsc.Pager(server.groups)}
        for name in manifest.get("groups", []):
            if name in existing_groups:
                planned.append(f"  = group exists     {name}")
                continue
            planned.append(f"  + group CREATE     {name}")
            if not dry_run:
                server.groups.create(tsc.GroupItem(name))

        # Datasources strictly before workbooks, so a workbook's published binding resolves.
        for kind, endpoint, item_cls in (
            ("datasource", server.datasources, tsc.DatasourceItem),
            ("workbook", server.workbooks, tsc.WorkbookItem),
        ):
            present = {(i.name, i.project_id) for i in tsc.Pager(endpoint)}
            for rec in [c for c in manifest["content"] if c["kind"] == kind]:
                segments = tuple(rec["project_path"])
                label = f"{show_path(segments)} > {rec['name']}"
                if rec["tableau_managed"]:
                    continue
                if not rec["filename"]:
                    problems.append(f"{kind} {label!r}: no captured file")
                    continue
                src = assets / rec["filename"]
                if not src.is_file():
                    problems.append(f"{kind} {label!r}: missing asset {src.name}")
                    continue
                project_id = path_to_id.get(segments)
                if project_id is None and not dry_run:
                    problems.append(f"{kind} {label!r}: project {show_path(segments)!r} not found")
                    continue
                if (rec["name"], project_id) in present and not overwrite:
                    planned.append(f"  = {kind} exists  {label}")
                    continue

                creds = _credentials_for(rec.get("content_type", ""), env) if rec["embed_credentials"] else None
                note = ""
                if (
                    rec["embed_credentials"]
                    and rec.get("content_type") in {"snowflake", "databricks"}
                    and creds is None
                ):
                    note = "  [WARN no credential in .env - will publish unauthenticated]"
                elif not rec["embed_credentials"]:
                    note = "  [fixture: intentionally no credentials]"
                planned.append(f"  + {kind} PUBLISH {label}{note}")
                if dry_run:
                    continue
                mode = "Overwrite" if overwrite else "CreateNew"
                item = item_cls(project_id)
                item.name = rec["name"]
                try:
                    if kind == "datasource":
                        endpoint.publish(item, str(src), mode, connection_credentials=creds)
                    else:
                        endpoint.publish(item, str(src), mode)
                except Exception as exc:  # pylint: disable=broad-except
                    problems.append(f"{kind} {label!r}: publish failed: {type(exc).__name__}: {exc}")

    print("\n".join(planned) or "  (nothing to do)")
    if problems:
        print(f"\n{len(problems)} problem(s):")
        for p in problems:
            print(f"  ! {p}")
    print(
        "\nNOT reproduced by design: permission rules and group MEMBERSHIP. "
        "User LUIDs differ on a fresh site, and a half-correct permission model is worse than an absent one."
    )
    return 1 if problems else 0


def empty_leaf_projects(server: Any) -> list[tuple[tuple[str, ...], str, str]]:
    """Return `(segments, project_id, name)` for every leaf project holding no content.

    A leaf with nothing in it is an inert fixture: the migration never walks that path, so whatever
    the folder was built to stress - 11 levels of nesting, a slash in the name - is never exercised.
    The project's own `name` is returned rather than derived from the path, because deriving it is
    what broke on `R/D`.
    """
    projects = list(tsc.Pager(server.projects))
    by_id = {p.id: p for p in projects}
    paths = {p.id: project_path_of(p, by_id) for p in projects}
    parents = {paths[p.parent_id] for p in projects if p.parent_id and p.parent_id in paths}

    counts = {pid: 0 for pid in paths}
    for endpoint in (server.datasources, server.workbooks):
        for item in tsc.Pager(endpoint):
            if item.project_id in counts:
                counts[item.project_id] += 1

    return sorted(
        (paths[pid], pid, by_id[pid].name)
        for pid, n in counts.items()
        if n == 0 and paths[pid] not in parents and not _managed(paths[pid]) and show_path(paths[pid]) not in KEEP_EMPTY
    )


def _publish_seed(server: Any, target: tuple[tuple[str, ...], str, str], work_dir: Path) -> str | None:
    """Publish one seed workbook. Returns an error string, or None on success."""
    from make_seed_workbook import build_twbx  # pylint: disable=import-outside-toplevel

    segments, project_id, leaf = target
    name = f"Seed - {leaf}"
    item = tsc.WorkbookItem(project_id)
    item.name = name
    try:
        server.workbooks.publish(item, str(build_twbx(name, work_dir / _safe_filename(name, ".twbx"))), "Overwrite")
    except Exception as exc:  # pylint: disable=broad-except
        return f"{show_path(segments)} > {name}: {type(exc).__name__}: {exc}"
    return None


def seed_empty_projects(env: dict[str, str], work_dir: Path, *, dry_run: bool) -> int:
    """Publish one tiny workbook into every empty leaf project, so each becomes migratable."""
    server, auth = _sign_in(env)
    problems: list[str] = []
    with server.auth.sign_in(auth):
        targets = empty_leaf_projects(server)
        if not targets:
            print("  (no empty leaf projects - nothing to seed)")
            return 0
        for target in targets:
            print(f"  + seed {'PLAN' if dry_run else 'PUBLISH'}  {show_path(target[0])} > Seed - {target[2]}")
            if dry_run:
                continue
            if (err := _publish_seed(server, target, work_dir)) is not None:
                problems.append(err)

    if problems:
        print(f"\n{len(problems)} problem(s):")
        for p in problems:
            print(f"  ! {p}")
    return 1 if problems else 0


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    cap = sub.add_parser("capture", help="enumerate the live site and download its assets")
    cap.add_argument("--out", type=Path, default=REPO_ROOT / "_runs" / "tableau-estate")
    cap.add_argument("--include-extract", action="store_true", help="include extract data in downloads")
    cap.add_argument("--no-download", action="store_true", help="write the manifest only")

    app = sub.add_parser("apply", help="recreate the estate from a manifest")
    app.add_argument("--manifest", type=Path, required=True)
    app.add_argument("--dry-run", action="store_true")
    app.add_argument("--overwrite", action="store_true", help="republish content that already exists")

    sd = sub.add_parser("seed", help="give every empty leaf project something migratable")
    sd.add_argument("--dry-run", action="store_true")
    sd.add_argument("--work-dir", type=Path, default=REPO_ROOT / "_runs" / "tableau-estate" / "seeds")

    args = parser.parse_args()
    env = resolve_env(REPO_ROOT / ".env")
    require(env, "TABLEAU_SITE", "TABLEAU_PAT_NAME")

    if args.command == "capture":
        out = args.out.resolve()
        manifest = capture(out, env, include_extract=args.include_extract, download=not args.no_download)
        target = out / "manifest.json"
        target.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf8")
        ours = [c for c in manifest["content"] if not c["tableau_managed"]]
        print(f"captured -> {target}")
        print(f"  projects {len(manifest['projects'])}  groups {len(manifest['groups'])}  content {len(ours)} (ours)")
        missing = [c for c in ours if not c["filename"]]
        if missing:
            print(f"  {len(missing)} asset(s) did not download:")
            for c in missing:
                print(f"    ! {show_path(c['project_path'])} > {c['name']}: {'; '.join(c['notes']) or 'unknown'}")
        return 0

    if args.command == "seed":
        args.work_dir.mkdir(parents=True, exist_ok=True)
        return seed_empty_projects(env, args.work_dir, dry_run=args.dry_run)

    manifest = json.loads(args.manifest.read_text(encoding="utf8"))
    return apply_manifest(
        manifest, args.manifest.parent / "assets", env, dry_run=args.dry_run, overwrite=args.overwrite
    )


if __name__ == "__main__":
    sys.exit(main())
